# Generated by Django 4.2.8 on 2023-12-06 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('name_local', models.CharField(blank=True, default='', max_length=256, verbose_name='Название (на этом языке)')),
                ('isocode', models.CharField(help_text='2 символьный код языка без страны', max_length=2, unique=True, verbose_name='ISO 639-1 код языка')),
                ('sorting', models.PositiveIntegerField(default=0, help_text='увеличьте, чтобы поднять в списке', verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
                'ordering': ('-sorting', 'name', 'isocode'),
            },
        ),
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date created')),
                ('is_native', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='languages.language', verbose_name='Язык')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
