# Generated by Django 4.2.6 on 2023-11-11 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Language name')),
                ('name_local', models.CharField(blank=True, default='', max_length=256, verbose_name='Language name (in that language)')),
                ('isocode', models.CharField(help_text='2 character language code without country', max_length=2, unique=True, verbose_name='ISO 639-1 Language code')),
                ('sorting', models.PositiveIntegerField(default=0, help_text='increase to show at top of the list', verbose_name='Sorting order')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
                'ordering': ('-sorting', 'name', 'isocode'),
            },
        ),
        migrations.CreateModel(
            name='UserLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date created')),
                ('is_native', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='languages.language', verbose_name='Language')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
