# Generated by Django 4.2.10 on 2024-04-20 13:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="Название")),
                (
                    "name_local",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Название (на этом языке)",
                    ),
                ),
                (
                    "isocode",
                    models.CharField(
                        help_text="2 символьный код языка без страны",
                        max_length=2,
                        unique=True,
                        verbose_name="ISO 639-1 код языка",
                    ),
                ),
                (
                    "sorting",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="увеличьте, чтобы поднять в списке",
                        verbose_name="Порядок сортировки",
                    ),
                ),
                (
                    "learning_available",
                    models.BooleanField(
                        default=False,
                        verbose_name="Is the language available for user to add to learning ones.",
                    ),
                ),
                (
                    "interface_available",
                    models.BooleanField(
                        default=False,
                        verbose_name="Is the language available as interface language.",
                    ),
                ),
                (
                    "flag_icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="languages/flag_icons/",
                        verbose_name="Language flag icon",
                    ),
                ),
            ],
            options={
                "verbose_name": "Язык",
                "verbose_name_plural": "Языки",
                "ordering": ("-sorting", "name", "isocode"),
            },
        ),
        migrations.CreateModel(
            name="LanguageImage",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Date modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="languages/images/", verbose_name="Language image"
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="languages.language",
                        verbose_name="Язык",
                    ),
                ),
            ],
            options={
                "verbose_name": "Language image",
                "verbose_name_plural": "Language images",
                "ordering": ("-created", "-modified"),
            },
        ),
    ]
