# Generated by Django 4.2.11 on 2024-05-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="isocode",
            field=models.CharField(
                help_text="2 символьный код языка без страны",
                max_length=8,
                unique=True,
                verbose_name="ISO 639-1 код языка",
            ),
        ),
    ]
