# Generated by Django 4.2.11 on 2024-07-06 07:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0002_alter_language_isocode"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="language",
            table_comment="Языки",
        ),
        migrations.AlterModelTableComment(
            name="languageimage",
            table_comment="Images available to be set as cover for the learning language",
        ),
    ]
