# Generated by Django 4.2.14 on 2024-07-29 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0003_alter_language_table_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="interface_available",
            field=models.BooleanField(
                default=False,
                verbose_name="Is the language available as interface language",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="learning_available",
            field=models.BooleanField(
                default=False,
                verbose_name="Is the language available for user to add to learning ones",
            ),
        ),
    ]
