# Generated by Django 4.2.14 on 2024-07-29 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0004_alter_language_interface_available_and_more"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="languageimage",
            table_comment="Картинки доступные для обновления обложки изучаемого языка",
        ),
    ]
