# Generated by Django 4.2.14 on 2024-07-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0005_alter_languageimage_table_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language",
            name="sorting",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Increase to show at top of the list",
                verbose_name="Порядок сортировки",
            ),
        ),
    ]
