# Generated by Django 4.2.14 on 2024-08-01 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0006_alter_language_sorting"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="languageimage",
            options={
                "ordering": ("-created", "-modified"),
                "verbose_name": "Картинка языка",
                "verbose_name_plural": "Languages images",
            },
        ),
        migrations.AlterField(
            model_name="language",
            name="flag_icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="languages/flag_icons/",
                verbose_name="Иконка флага языка",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="interface_available",
            field=models.BooleanField(
                default=False, verbose_name="Язык доступен для перевода интерфейса"
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="learning_available",
            field=models.BooleanField(
                default=False, verbose_name="Язык доступен для добавления в изучаемые"
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(max_length=256, verbose_name="Название языка"),
        ),
        migrations.AlterField(
            model_name="language",
            name="name_local",
            field=models.CharField(
                blank=True,
                default="",
                max_length=256,
                verbose_name="Название языка (на этом языке)",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="sorting",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Увеличьте, чтобы поднять в списке",
                verbose_name="Порядок сортировки",
            ),
        ),
        migrations.AlterField(
            model_name="languageimage",
            name="image",
            field=models.ImageField(
                height_field="height",
                upload_to="languages/images/",
                verbose_name="Картинка языка",
                width_field="width",
            ),
        ),
    ]
