# Generated by Django 4.2.14 on 2024-08-01 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "languages",
            "0007_alter_languageimage_options_alter_language_flag_icon_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="languageimage",
            name="image",
            field=models.ImageField(
                upload_to="languages/images/", verbose_name="Картинка языка"
            ),
        ),
    ]
