# Generated by Django 4.2.14 on 2024-08-18 12:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0008_alter_languageimage_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="languageimage",
            options={
                "ordering": ("-created", "-modified"),
                "verbose_name": "Картинка языка",
                "verbose_name_plural": "Картинки языков",
            },
        ),
    ]
