# Generated by Django 4.2.14 on 2024-08-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0009_alter_languageimage_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="name_en",
            field=models.CharField(
                max_length=256, null=True, verbose_name="Название языка"
            ),
        ),
        migrations.AddField(
            model_name="language",
            name="name_ru",
            field=models.CharField(
                max_length=256, null=True, verbose_name="Название языка"
            ),
        ),
    ]
