# Generated by Django 4.2.14 on 2024-08-26 08:40

from django.db import migrations, models
import languages.models


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0010_language_name_en_language_name_ru"),
    ]

    operations = [
        migrations.AlterField(
            model_name="languageimage",
            name="image",
            field=models.ImageField(
                upload_to=languages.models.language_images_path,
                verbose_name="Картинка языка",
            ),
        ),
    ]
