# Generated by Django 4.2.10 on 2024-04-21 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="slug",
        ),
    ]
