# Generated by Django 4.2.11 on 2024-07-06 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_remove_user_slug"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="user",
            table_comment="Пользователи",
        ),
        migrations.AlterModelTableComment(
            name="userdefaultwordsview",
            table_comment="Default word cards view for the user",
        ),
        migrations.AlterModelTableComment(
            name="userlearninglanguage",
            table_comment="Users learning languages",
        ),
        migrations.AlterModelTableComment(
            name="usernativelanguage",
            table_comment="Users native languages",
        ),
        migrations.RemoveField(
            model_name="userlearninglanguage",
            name="image",
        ),
        migrations.AddField(
            model_name="userlearninglanguage",
            name="cover",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/languages/images/",
                verbose_name="Learning language cover image",
            ),
        ),
    ]
