# Generated by Django 4.2.8 on 2024-02-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                null=True,
                verbose_name="Пол",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/profile-images/",
                verbose_name="Картинка профиля",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="slug",
            field=models.SlugField(max_length=255, verbose_name="Слаг"),
        ),
    ]
