# Generated by Django 4.2.11 on 2024-07-11 09:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_table_comment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "get_latest_by": ("created", "date_joined"),
                "ordering": ("-date_joined",),
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
