# Generated by Django 4.2.14 on 2024-07-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0003_alter_language_table_comment_and_more"),
        ("users", "0005_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userdefaultwordsview",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "User default word cards view setting",
                "verbose_name_plural": "User default word cards view settings",
            },
        ),
        migrations.AlterModelOptions(
            name="userlearninglanguage",
            options={
                "ordering": ("-created", "-modified"),
                "verbose_name": "Изучаемый язык",
                "verbose_name_plural": "Изучаемые языки",
            },
        ),
        migrations.AlterModelOptions(
            name="usernativelanguage",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Родной язык",
                "verbose_name_plural": "Родные языки",
            },
        ),
        migrations.AlterModelTableComment(
            name="userdefaultwordsview",
            table_comment="Вид карточек слов по умолчанию для пользователя",
        ),
        migrations.AlterModelTableComment(
            name="userlearninglanguage",
            table_comment="Изучаемые языки",
        ),
        migrations.AlterModelTableComment(
            name="usernativelanguage",
            table_comment="Родные языки",
        ),
        migrations.AlterField(
            model_name="user",
            name="learning_languages",
            field=models.ManyToManyField(
                blank=True,
                related_name="learning_by",
                through="users.UserLearningLanguage",
                to="languages.language",
                verbose_name="Изучаемые языки",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="native_languages",
            field=models.ManyToManyField(
                blank=True,
                related_name="native_for",
                through="users.UserNativeLanguage",
                to="languages.language",
                verbose_name="Родные языки",
            ),
        ),
        migrations.AlterField(
            model_name="userdefaultwordsview",
            name="words_view",
            field=models.CharField(
                choices=[
                    ("standart", "Стандартный"),
                    ("short", "Короткий"),
                    ("long", "Удлиненный"),
                ],
                default="standart",
                max_length=8,
                verbose_name="Word cards view",
            ),
        ),
        migrations.AlterField(
            model_name="userlearninglanguage",
            name="cover",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/languages/images/",
                verbose_name="Обложка изучаемого языка",
            ),
        ),
        migrations.AlterField(
            model_name="userlearninglanguage",
            name="level",
            field=models.CharField(
                blank=True,
                default="",
                max_length=256,
                null=True,
                verbose_name="Уровень владения",
            ),
        ),
    ]
