# Generated by Django 4.2.14 on 2024-07-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_userdefaultwordsview_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userdefaultwordsview",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Настройка вида карточек слов по умолчанию",
                "verbose_name_plural": "Настройки вида карточек слов по умолчанию",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Почта"),
        ),
        migrations.AlterField(
            model_name="userdefaultwordsview",
            name="words_view",
            field=models.CharField(
                choices=[
                    ("standart", "Стандартный"),
                    ("short", "Короткий"),
                    ("long", "Удлиненный"),
                ],
                default="standart",
                max_length=8,
                verbose_name="Вид карточек слов",
            ),
        ),
    ]
