# Generated by Django 4.2.14 on 2024-08-19 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0009_alter_languageimage_options"),
        ("users", "0007_alter_userdefaultwordsview_options_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlearninglanguage",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="covers",
                to="languages.languageimage",
                verbose_name="Обложка изучаемого языка",
            ),
        ),
    ]
