# Generated by Django 4.2.14 on 2024-08-26 08:40

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_userlearninglanguage_cover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=users.models.user_profile_images_path,
                verbose_name="Картинка профиля",
            ),
        ),
    ]
