# Generated by Django 4.2.15 on 2024-12-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_interface_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="interface_language",
            field=models.CharField(
                choices=[("ru", "Russian"), ("en", "English")],
                default="ru",
                max_length=8,
                verbose_name="Interface language",
            ),
        ),
    ]
