# Generated by Django 4.2.15 on 2024-12-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0007_alter_userlearninglanguage_options_and_more"),
        ("users", "0005_alter_user_interface_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="learning_languages",
            field=models.ManyToManyField(
                blank=True,
                related_name="learning_by",
                through="languages.UserLearningLanguage",
                to="languages.language",
                verbose_name="Изучаемые языки пользователей",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="native_languages",
            field=models.ManyToManyField(
                blank=True,
                related_name="native_for",
                through="languages.UserNativeLanguage",
                to="languages.language",
                verbose_name="Родные языки пользователей",
            ),
        ),
    ]
