# Generated by Django 4.2.15 on 2024-12-16 09:50

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0008_alter_language_options_and_more"),
        ("users", "0006_alter_user_learning_languages_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "get_latest_by": ("created", "date_joined"),
                "ordering": ("-date_joined",),
                "verbose_name": "User",
                "verbose_name_plural": "Users",
            },
        ),
        migrations.AlterModelTableComment(
            name="user",
            table_comment="Users",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                null=True,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.users.models.user_profile_images_path,
                verbose_name="Profile image",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="learning_languages",
            field=models.ManyToManyField(
                blank=True,
                related_name="learning_by",
                through="languages.UserLearningLanguage",
                to="languages.language",
                verbose_name="Users learning languages",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="native_languages",
            field=models.ManyToManyField(
                blank=True,
                related_name="native_for",
                through="languages.UserNativeLanguage",
                to="languages.language",
                verbose_name="Users native languages",
            ),
        ),
    ]
