FROM python:3.10-slim

WORKDIR /app

COPY ./requirements.txt .

RUN pip3 install -r requirements.txt --no-cache-dir

COPY . .

ENV DATABASE_URL=$DATABASE_URL

RUN python manage.py collectstatic --no-input
RUN python manage.py migrate
RUN python manage.py importexercises
RUN python manage.py importlanguages
RUN python manage.py importwordtypes
RUN python manage.py makesuperuser

EXPOSE 8000

CMD export && (gunicorn --log-level debug --bind 0.0.0.0:8000 config.wsgi)
