FROM python:3.10-slim

WORKDIR /app

COPY ./requirements.txt .

RUN pip3 install -r requirements.txt --no-cache-dir

COPY src/ .

ENV DATABASE_URL postgresql://linguista_db_user:gW8u9rifM0xUh4ut1KuOuvX9kq4dEK6k@dpg-cra3oka3esus739qe2p0-a/linguista_db_uamm

RUN python manage.py collectstatic --no-input
RUN python manage.py migrate
RUN python manage.py importexercises
RUN python manage.py importlanguages
RUN python manage.py importwordtypes
RUN python manage.py makesuperuser

EXPOSE 8000

CMD export && (gunicorn --log-level debug --bind 0.0.0.0:8000 config.wsgi)
