databases:
  - name: postgres
    databaseName: postgres_db_hdvk
    user: postgres_user

services:
  - type: web
    name: linguista
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres_db_hdvk
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
