databases:
  - name: postgres
    databaseName: postgres_db_hdvk
    user: postgres_user

services:
  - type: web
    name: linguista_docker
    runtime: docker
    repo: https://github.com/FSD-For-Self-Dev/LinguistaAPI.git
    branch: develop
    envVars:
      - fromGroup: conc-settings
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString

envVarGroups:
  - name: conc-settings
    envVars:
      - key: CONCURRENCY
        value: 2
      - key: SECRET
        generateValue: true
  - name: stripe
    envVars:
      - key: STRIPE_API_URL
        value: https://api.stripe.com/v2
