# Generated by Django 4.2.14 on 2024-08-31 07:02

import apps.core.models
import apps.languages.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=256, verbose_name="Название языка"),
                ),
                (
                    "name_ru",
                    models.CharField(
                        max_length=256, null=True, verbose_name="Название языка"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=256, null=True, verbose_name="Название языка"
                    ),
                ),
                (
                    "name_local",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=256,
                        verbose_name="Название языка (на этом языке)",
                    ),
                ),
                (
                    "isocode",
                    models.CharField(
                        help_text="2 символьный код языка без страны",
                        max_length=8,
                        unique=True,
                        verbose_name="ISO 639-1 код языка",
                    ),
                ),
                (
                    "sorting",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Увеличьте, чтобы поднять в списке",
                        verbose_name="Порядок сортировки",
                    ),
                ),
                (
                    "learning_available",
                    models.BooleanField(
                        default=False,
                        verbose_name="Язык доступен для добавления в изучаемые",
                    ),
                ),
                (
                    "interface_available",
                    models.BooleanField(
                        default=False,
                        verbose_name="Язык доступен для перевода интерфейса",
                    ),
                ),
                (
                    "flag_icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="languages/flag_icons/",
                        verbose_name="Иконка флага языка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Язык",
                "verbose_name_plural": "Языки",
                "db_table_comment": "Языки",
                "ordering": ("-sorting", "name", "isocode"),
            },
            bases=(apps.core.models.WordsCountMixin, models.Model),
        ),
        migrations.CreateModel(
            name="LanguageImage",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Date modified"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.languages.models.language_images_path,
                        verbose_name="Картинка языка",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="languages.language",
                        verbose_name="Язык",
                    ),
                ),
            ],
            options={
                "verbose_name": "Картинка языка",
                "verbose_name_plural": "Картинки языков",
                "db_table_comment": "Картинки доступные для обновления обложки изучаемого языка",
                "ordering": ("-created", "-modified"),
            },
        ),
    ]
