# Generated by Django 4.2.15 on 2024-09-01 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("languages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userlearninglanguage",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_languages_detail",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usernativelanguage",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="native_languages_detail",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="userlearninglanguage",
            constraint=models.UniqueConstraint(
                models.F("language"),
                models.F("user"),
                name="unique_user_learning_language",
            ),
        ),
        migrations.AddConstraint(
            model_name="usernativelanguage",
            constraint=models.UniqueConstraint(
                models.F("language"),
                models.F("user"),
                name="unique_user_native_language",
            ),
        ),
    ]
