# Generated by Django 4.2.15 on 2024-12-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0004_alter_language_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="country",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="Country name"
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="isocode",
            field=models.CharField(
                help_text="2 or 3 character language code with 2 character country code",
                max_length=8,
                unique=True,
                verbose_name="ISO 639-1 код языка",
            ),
        ),
    ]
