# Generated by Django 4.2.15 on 2024-12-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0005_language_country_alter_language_isocode"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="country_en",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Country name"
            ),
        ),
        migrations.AddField(
            model_name="language",
            name="country_ru",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Country name"
            ),
        ),
    ]
