# Generated by Django 4.2.15 on 2024-12-16 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0006_language_country_en_language_country_ru"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userlearninglanguage",
            options={
                "ordering": ("-created", "-modified"),
                "verbose_name": "Изучаемый язык пользователя",
                "verbose_name_plural": "Изучаемые языки пользователя",
            },
        ),
        migrations.AlterModelOptions(
            name="usernativelanguage",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Родной язык пользователя",
                "verbose_name_plural": "Родные языки пользователя",
            },
        ),
        migrations.AlterModelTableComment(
            name="userlearninglanguage",
            table_comment="Изучаемые языки пользователей",
        ),
        migrations.AlterModelTableComment(
            name="usernativelanguage",
            table_comment="Родные языки пользователей",
        ),
        migrations.AlterField(
            model_name="language",
            name="country",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="Название страны"
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="country_en",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Название страны"
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="country_ru",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Название страны"
            ),
        ),
        migrations.AlterField(
            model_name="userlearninglanguage",
            name="cover",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="covers",
                to="languages.languagecoverimage",
                verbose_name="Learning language cover image",
            ),
        ),
    ]
