# Generated by Django 4.2.15 on 2024-12-16 09:41

import apps.languages.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("languages", "0007_alter_userlearninglanguage_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="language",
            options={
                "get_latest_by": ("name",),
                "ordering": ("-sorting", "name", "isocode"),
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
            },
        ),
        migrations.AlterModelOptions(
            name="languagecoverimage",
            options={
                "ordering": ("-created", "-modified"),
                "verbose_name": "Language image",
                "verbose_name_plural": "Languages images",
            },
        ),
        migrations.AlterModelOptions(
            name="userlearninglanguage",
            options={
                "ordering": ("-created", "-modified"),
                "verbose_name": "User learning language",
                "verbose_name_plural": "User learning languages",
            },
        ),
        migrations.AlterModelOptions(
            name="usernativelanguage",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "User native language",
                "verbose_name_plural": "User native languages",
            },
        ),
        migrations.AlterModelTableComment(
            name="language",
            table_comment="Languages",
        ),
        migrations.AlterModelTableComment(
            name="languagecoverimage",
            table_comment="Images available to be set as cover for the learning language",
        ),
        migrations.AlterModelTableComment(
            name="userlearninglanguage",
            table_comment="Users learning languages",
        ),
        migrations.AlterModelTableComment(
            name="usernativelanguage",
            table_comment="Users native languages",
        ),
        migrations.AlterField(
            model_name="language",
            name="country",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="Country name"
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="country_en",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Country name"
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="country_ru",
            field=models.CharField(
                blank=True, max_length=256, null=True, verbose_name="Country name"
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="flag_icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="languages/flag_icons/",
                verbose_name="Language flag icon",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="interface_available",
            field=models.BooleanField(
                default=False,
                verbose_name="Is the language available as interface language",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="isocode",
            field=models.CharField(
                help_text="2 or 3 character language code with 2 character country code",
                max_length=8,
                unique=True,
                verbose_name="ISO 639-1 Language code",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="learning_available",
            field=models.BooleanField(
                default=False,
                verbose_name="Is the language available for user to add to learning ones",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="name",
            field=models.CharField(max_length=256, verbose_name="Language name"),
        ),
        migrations.AlterField(
            model_name="language",
            name="name_en",
            field=models.CharField(
                max_length=256, null=True, verbose_name="Language name"
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="name_local",
            field=models.CharField(
                blank=True,
                default="",
                max_length=256,
                verbose_name="Language name (in that language)",
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="name_ru",
            field=models.CharField(
                max_length=256, null=True, verbose_name="Language name"
            ),
        ),
        migrations.AlterField(
            model_name="language",
            name="sorting",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Increase to show at top of the list",
                verbose_name="Sorting order",
            ),
        ),
        migrations.AlterField(
            model_name="languagecoverimage",
            name="image",
            field=models.ImageField(
                upload_to=apps.languages.models.language_images_path,
                verbose_name="Language image",
            ),
        ),
        migrations.AlterField(
            model_name="languagecoverimage",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="languages.language",
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="userlearninglanguage",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_by_detail",
                to="languages.language",
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="userlearninglanguage",
            name="level",
            field=models.CharField(
                blank=True,
                default="",
                max_length=256,
                null=True,
                verbose_name="Level of knowledge",
            ),
        ),
        migrations.AlterField(
            model_name="userlearninglanguage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="learning_languages_detail",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="usernativelanguage",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="native_for_detail",
                to="languages.language",
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="usernativelanguage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="native_languages_detail",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
