# Generated by Django 4.2.15 on 2024-12-17 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("languages", "0009_alter_language_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="languagecoverimage",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
            preserve_default=False,
        ),
    ]
