version: '3.8'
services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - /var/lib/postgresql/data/
    restart: always
    env_file:
      - ./.env

  app:
    build: ..
    ports:
     - "8000:80"
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  # frontend:
  #   ...

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    depends_on:
      - app
      # - frontend

volumes:
  static_value:
  media_value:
