# Запуск контейнеров из образов dockerhub

version: '3.8'
services:
  db:
    image: postgres:12.1-alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env

  app:
    image: fsdforselfdev/linguista:latest
    pull_policy: always
    ports:
     - "8000:8000"
    restart: always
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  # this service will use same image, and once the migration is done it will be stopped
  app_migrations:
    image: fsdforselfdev/linguista:latest
    pull_policy: always
    command:
    - /bin/sh
    - -c
    - |
      python manage.py migrate
      python manage.py collectstatic --no-input
      python manage.py importexercises
      python manage.py importlanguages
      python manage.py importwordtypes
      python manage.py makesuperuser
    volumes:
      - static_volume:/app/static/
    depends_on:
      - app
      - db
    env_file:
      - ./.env

  nginx:
    image: fsdforselfdev/linguista-frontend:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/var/html/static/
      - media_volume:/var/html/media/
    depends_on:
      - app

volumes:
  static_volume:
  media_volume:
  db_volume:
