version: '3.8'
services:
  db:
    image: postgres:12.1-alpine
    ports:
      - "5432:5432"
    restart: unless-stoped
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./.env

  app:
    build:
      context: .
      dockerfile: ../Dockerfile
    ports:
     - "8000:8000"
    restart: unless-stoped
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  # this service will use same image as web app, and once the migration is done it will be stopped
  app_migrations:
    build:
      context: .
      dockerfile: ../Dockerfile
    command: bash -c "python manage.py migrate && python manage.py loaddata data_dump.json && python manage.py collectstatic --no-input"
    depends_on:
      - app
      - db
    env_file:
      - ./.env

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    restart: unless-stoped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      # - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - app

volumes:
  static_value:
  media_value:
