version: '3.8'
services:
  db:
    image: postgres:11.1-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # env_file:
    #   - ./.env
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  app:
    image: fsdforselfdev/linguista:latest
    restart: always
    volumes:
      - static_value:/linguista/static/
      - media_value:/linguista/media/
    depends_on:
      - db
    env_file:
      - ./.env

  # frontend:
  #   ...

  nginx:
    # image: whywe-nginx:latest
    # build:
    #   context: .
    #   dockerfile: nginx/Dockerfile
    image: nginx:1.21-alpine
    # image: nginx:1.21.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    depends_on:
      - app
      # - frontend

volumes:
  static_value:
  media_value:
  postgres_data:
