"""Vocabulary app constants."""


class VocabularyLengthLimits:
    """Length limits constants."""

    MAX_WORD_LENGTH = 256
    MIN_WORD_LENGTH = 1
    MAX_TRANSLATION_LENGTH = 256
    MIN_TRANSLATION_LENGTH = 1
    MAX_DEFINITION_LENGTH = 512
    MIN_DEFINITION_LENGTH = 2
    MAX_EXAMPLE_LENGTH = 512
    MIN_EXAMPLE_LENGTH = 2
    MAX_NOTE_LENGTH = 256
    MIN_NOTE_LENGTH = 1
    MAX_COLLECTION_TITLE_LENGTH = 32
    MIN_COLLECTION_TITLE_LENGTH = 1
    MAX_COLLECTION_DESCRIPTION_LENGTH = 128
    MAX_TAG_LENGTH = 32
    MIN_TAG_LENGTH = 1
    MAX_FORMSGROUP_NAME_LENGTH = 64
    MIN_FORMSGROUP_NAME_LENGTH = 1
    MAX_QUOTE_TEXT_LENGTH = 256
    MAX_QUOTE_AUTHOR_LENGTH = 64
