# Generated by Django 4.2.10 on 2024-04-20 13:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Date modified"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256, verbose_name="Название упражнения"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=4096, verbose_name="Описание"),
                ),
                (
                    "constraint_description",
                    models.CharField(
                        blank=True,
                        max_length=512,
                        verbose_name="Constraint description",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="exercises/icons/",
                        verbose_name="Exercise icon",
                    ),
                ),
                (
                    "available",
                    models.BooleanField(
                        default=False,
                        verbose_name="Is the exercise available for users.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Упражнение",
                "verbose_name_plural": "Упражнения",
                "ordering": ("-created",),
                "get_latest_by": ("created", "modified"),
            },
        ),
        migrations.CreateModel(
            name="FavoriteExercise",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранное упражнение",
                "verbose_name_plural": "Избранные упражнения",
                "ordering": ["-created"],
                "get_latest_by": ["created"],
            },
        ),
        migrations.CreateModel(
            name="Hint",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Hint name"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=128, verbose_name="Hint details"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=16, unique=True, verbose_name="Hint short code"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hint",
                "verbose_name_plural": "Hints",
                "ordering": ("-created",),
                "get_latest_by": ("created",),
            },
        ),
        migrations.CreateModel(
            name="TranslatorHistoryDetails",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_answer", models.CharField(max_length=512)),
                ("suggested_options", models.JSONField(blank=True)),
                ("answer_time", models.TimeField(verbose_name="User answer time")),
            ],
            options={
                "verbose_name": "Translator exercise history",
                "verbose_name_plural": "Translator exercise history",
                "ordering": ("-created",),
                "get_latest_by": ("created",),
            },
        ),
        migrations.CreateModel(
            name="TranslatorUserDefaultSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("free", "Free input"),
                            ("variants", "Choose from variants"),
                        ],
                        default="free",
                        max_length=32,
                        verbose_name="Exercise chosen mode",
                    ),
                ),
                ("answer_time_limit", models.TimeField(verbose_name="Set time limit")),
                (
                    "repetitions_amount",
                    models.IntegerField(verbose_name="Every word repetitions amount"),
                ),
                (
                    "from_language",
                    models.CharField(
                        choices=[
                            ("LTN", "From learning"),
                            ("NTL", "From native"),
                            ("LTL", "From learning to learning"),
                            ("A", "Alternately"),
                        ],
                        default="LTN",
                        max_length=32,
                        verbose_name="Translate from learning or native language",
                    ),
                ),
            ],
            options={
                "verbose_name": "Translator exercise saved user settings",
                "verbose_name_plural": "Translator exercise saved users settings",
            },
        ),
        migrations.CreateModel(
            name="UsersExercisesHistory",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "words_amount",
                    models.IntegerField(verbose_name="Words in exercise amount"),
                ),
                (
                    "corrects_amount",
                    models.IntegerField(verbose_name="Correct answers amount"),
                ),
                (
                    "incorrects_amount",
                    models.IntegerField(verbose_name="Incorrect answers amount"),
                ),
                ("answer_time_limit", models.TimeField(verbose_name="Set time limit")),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("free", "Free input"),
                            ("variants", "Choose from variants"),
                        ],
                        default="free",
                        max_length=32,
                        verbose_name="Exercise chosen mode",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_history",
                        to="exercises.exercise",
                        verbose_name="Упражнение",
                    ),
                ),
            ],
            options={
                "verbose_name": "User exercise approach",
                "verbose_name_plural": "Users exercise approaches",
                "ordering": ("-created",),
                "get_latest_by": ("created",),
            },
        ),
    ]
