# Generated by Django 4.2.6 on 2023-11-11 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date created')),
                ('modified', models.DateTimeField(auto_now=True, null=True, verbose_name='Date modified')),
                ('name', models.CharField(max_length=256, verbose_name='Exercise name')),
                ('description', models.CharField(max_length=4096, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
                'ordering': ['-created'],
                'get_latest_by': ['created', 'modified'],
            },
        ),
        migrations.CreateModel(
            name='FavoriteExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date created')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_for', to='exercises.exercise', verbose_name='Exercise')),
            ],
            options={
                'verbose_name': 'Favorite exercise',
                'verbose_name_plural': 'Favorite exercises',
                'ordering': ['-created'],
                'get_latest_by': ['created'],
            },
        ),
    ]
