# Generated by Django 4.2.10 on 2024-04-22 07:04

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0002_word_last_exercise_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordSet",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date created"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Word set name")),
                (
                    "last_exercise_date",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="Last exercise date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Word set",
                "verbose_name_plural": "Word sets",
                "ordering": ("-last_exercise_date", "-created"),
                "get_latest_by": ("created",),
            },
            bases=(core.models.GetObjectBySlugModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="WordsUpdateHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_status",
                    models.CharField(
                        choices=[
                            ("I", "Неактивное"),
                            ("A", "Активное"),
                            ("M", "Усвоенное"),
                        ],
                        default="I",
                        max_length=8,
                        verbose_name="Статус активности",
                    ),
                ),
                (
                    "new_activity_status",
                    models.CharField(
                        choices=[
                            ("I", "Неактивное"),
                            ("A", "Активное"),
                            ("M", "Усвоенное"),
                        ],
                        default="A",
                        max_length=8,
                        verbose_name="Статус активности",
                    ),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="favoriteexercise",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Избранное упражнение",
                "verbose_name_plural": "Избранные упражнения",
            },
        ),
        migrations.AddField(
            model_name="exercise",
            name="hints_available",
            field=models.ManyToManyField(
                blank=True,
                related_name="exercises",
                to="exercises.hint",
                verbose_name="Exercise available hints",
            ),
        ),
        migrations.AddField(
            model_name="favoriteexercise",
            name="exercise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_for",
                to="exercises.exercise",
                verbose_name="Упражнение",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="favoriteexercise",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_exercises",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="translatorhistorydetails",
            name="approach",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="exercises.usersexerciseshistory",
                verbose_name="Approach",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="translatorhistorydetails",
            name="hints_used",
            field=models.ManyToManyField(
                blank=True,
                related_name="history",
                to="exercises.hint",
                verbose_name="Hints used",
            ),
        ),
        migrations.AddField(
            model_name="translatorhistorydetails",
            name="word",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises_history",
                to="vocabulary.word",
                verbose_name="Слово",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="translatoruserdefaultsettings",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translator_settings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usersexerciseshistory",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises_history",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="translatoruserdefaultsettings",
            name="mode",
            field=models.CharField(
                choices=[
                    ("free input", "Free input"),
                    ("variants", "Choose from variants"),
                ],
                default="free input",
                max_length=32,
                verbose_name="Exercise chosen mode",
            ),
        ),
        migrations.AlterField(
            model_name="translatoruserdefaultsettings",
            name="set_time_limit",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Set time limit"
            ),
        ),
        migrations.AlterField(
            model_name="usersexerciseshistory",
            name="mode",
            field=models.CharField(
                choices=[
                    ("free input", "Free input"),
                    ("variants", "Choose from variants"),
                ],
                default="free input",
                max_length=32,
                verbose_name="Exercise chosen mode",
            ),
        ),
        migrations.AlterField(
            model_name="usersexerciseshistory",
            name="set_time_limit",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Set time limit"
            ),
        ),
        migrations.AddConstraint(
            model_name="translatoruserdefaultsettings",
            constraint=models.UniqueConstraint(
                models.F("user"), name="unique_user_translator_settings"
            ),
        ),
        migrations.AddField(
            model_name="wordsupdatehistory",
            name="approach",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="words_updates",
                to="exercises.usersexerciseshistory",
                verbose_name="Approach",
            ),
        ),
        migrations.AddField(
            model_name="wordsupdatehistory",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="update_history",
                to="vocabulary.word",
                verbose_name="Слово",
            ),
        ),
        migrations.AddField(
            model_name="wordset",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="wordset",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="word_sets",
                to="exercises.exercise",
                verbose_name="Упражнение",
            ),
        ),
        migrations.AddField(
            model_name="wordset",
            name="words",
            field=models.ManyToManyField(
                related_name="sets", to="vocabulary.word", verbose_name="Set words"
            ),
        ),
    ]
