# Generated by Django 4.2.8 on 2023-12-15 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'get_latest_by': ['created', 'modified'], 'ordering': ['-created'], 'verbose_name': 'Exercise', 'verbose_name_plural': 'Exercises'},
        ),
        migrations.AlterModelOptions(
            name='favoriteexercise',
            options={'get_latest_by': ['created'], 'ordering': ['-created'], 'verbose_name': 'Favorite exercise', 'verbose_name_plural': 'Favorite exercises'},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.CharField(max_length=4096, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=256, verbose_name='Exercise name'),
        ),
        migrations.AlterField(
            model_name='favoriteexercise',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_for', to='exercises.exercise', verbose_name='Exercise'),
        ),
    ]
