# Generated by Django 4.2.11 on 2024-05-25 14:08

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WordSet",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date created"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Word set name")),
                (
                    "last_exercise_date",
                    models.DateTimeField(
                        editable=False, null=True, verbose_name="Last exercise date"
                    ),
                ),
            ],
            options={
                "verbose_name": "Word set",
                "verbose_name_plural": "Word sets",
                "ordering": ("-last_exercise_date", "-created"),
                "get_latest_by": ("created",),
            },
            bases=(core.models.GetObjectBySlugModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="WordsUpdateHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date created"
                    ),
                ),
                (
                    "activity_status",
                    models.CharField(
                        choices=[
                            ("I", "Неактивное"),
                            ("A", "Активное"),
                            ("M", "Усвоенное"),
                        ],
                        default="I",
                        max_length=8,
                        verbose_name="Статус активности",
                    ),
                ),
                (
                    "new_activity_status",
                    models.CharField(
                        choices=[
                            ("I", "Неактивное"),
                            ("A", "Активное"),
                            ("M", "Усвоенное"),
                        ],
                        default="A",
                        max_length=8,
                        verbose_name="Статус активности",
                    ),
                ),
            ],
            options={
                "verbose_name": "Word activity status upgrade history",
                "verbose_name_plural": "Words activity statuses upgrades history",
                "ordering": ("-created",),
                "get_latest_by": ("created",),
            },
        ),
        migrations.AlterModelOptions(
            name="favoriteexercise",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Избранное упражнение",
                "verbose_name_plural": "Избранные упражнения",
            },
        ),
        migrations.AlterModelOptions(
            name="translatorhistorydetails",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Translator history detail",
                "verbose_name_plural": "Translator history details",
            },
        ),
        migrations.AddField(
            model_name="exercise",
            name="hints_available",
            field=models.ManyToManyField(
                blank=True,
                related_name="exercises",
                to="exercises.hint",
                verbose_name="Exercise available hints",
            ),
        ),
        migrations.AddField(
            model_name="favoriteexercise",
            name="exercise",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_for",
                to="exercises.exercise",
                verbose_name="Упражнение",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="favoriteexercise",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_exercises",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="translatorhistorydetails",
            name="approach",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="exercises.usersexerciseshistory",
                verbose_name="Approach",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="translatorhistorydetails",
            name="hints_used",
            field=models.ManyToManyField(
                blank=True,
                related_name="history",
                to="exercises.hint",
                verbose_name="Hints used",
            ),
        ),
    ]
