# Generated by Django 4.2.10 on 2024-04-22 07:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0002_wordset_wordsupdatehistory_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wordsupdatehistory",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Word activity status upgrade history",
                "verbose_name_plural": "Words activity statuses upgrades history",
            },
        ),
        migrations.AddField(
            model_name="wordsupdatehistory",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Date created",
            ),
            preserve_default=False,
        ),
    ]
