# Generated by Django 4.2.11 on 2024-05-25 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0002_wordset_wordsupdatehistory_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vocabulary", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="translatorhistorydetails",
            name="task_translation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises_history",
                to="vocabulary.wordtranslation",
                verbose_name="Перевод слова",
            ),
        ),
        migrations.AddField(
            model_name="translatorhistorydetails",
            name="task_word",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises_history",
                to="vocabulary.word",
                verbose_name="Слово",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="translatorhistorydetails",
            name="verdict",
            field=models.CharField(
                choices=[("C", "Correct"), ("I", "Incorrect"), ("SC", "Semi-correct")],
                default=1,
                max_length=2,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="translatoruserdefaultsettings",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translator_settings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usersexerciseshistory",
            name="complete_time",
            field=models.TimeField(
                blank=True,
                null=True,
                verbose_name="The time in which the exercise was completed",
            ),
        ),
        migrations.AddField(
            model_name="usersexerciseshistory",
            name="hints_available",
            field=models.ManyToManyField(
                blank=True,
                related_name="approaches",
                to="exercises.hint",
                verbose_name="Approach available hints",
            ),
        ),
        migrations.AddField(
            model_name="usersexerciseshistory",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises_history",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hint",
            name="code",
            field=models.CharField(
                max_length=32, unique=True, verbose_name="Hint short code"
            ),
        ),
        migrations.AlterField(
            model_name="translatorhistorydetails",
            name="answer_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="User answer time"
            ),
        ),
        migrations.AlterField(
            model_name="translatorhistorydetails",
            name="suggested_options",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="translatoruserdefaultsettings",
            name="mode",
            field=models.CharField(
                choices=[
                    ("FI", "Free input (one translation is enough)"),
                    ("FIM", "Free input (maximum translations quantity)"),
                    ("V", "Choose from variants"),
                ],
                default="FI",
                max_length=32,
                verbose_name="Exercise chosen mode",
            ),
        ),
        migrations.AlterField(
            model_name="translatoruserdefaultsettings",
            name="repetitions_amount",
            field=models.SmallIntegerField(
                default=1, verbose_name="Every word repetitions amount"
            ),
        ),
        migrations.AlterField(
            model_name="translatoruserdefaultsettings",
            name="answer_time_limit",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Set time limit"
            ),
        ),
        migrations.AlterField(
            model_name="usersexerciseshistory",
            name="mode",
            field=models.CharField(
                choices=[
                    ("FI", "Free input (one translation is enough)"),
                    ("FIM", "Free input (maximum translations quantity)"),
                    ("V", "Choose from variants"),
                ],
                default="FI",
                max_length=3,
                verbose_name="Exercise chosen mode",
            ),
        ),
        migrations.AlterField(
            model_name="usersexerciseshistory",
            name="answer_time_limit",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Set time limit"
            ),
        ),
        migrations.AddConstraint(
            model_name="translatoruserdefaultsettings",
            constraint=models.UniqueConstraint(
                models.F("user"), name="unique_user_translator_settings"
            ),
        ),
        migrations.AddField(
            model_name="wordsupdatehistory",
            name="approach",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="words_updates",
                to="exercises.usersexerciseshistory",
                verbose_name="Approach",
            ),
        ),
        migrations.AddField(
            model_name="wordsupdatehistory",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="update_history",
                to="vocabulary.word",
                verbose_name="Слово",
            ),
        ),
        migrations.AddField(
            model_name="wordset",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AddField(
            model_name="wordset",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="word_sets",
                to="exercises.exercise",
                verbose_name="Упражнение",
            ),
        ),
        migrations.AddField(
            model_name="wordset",
            name="words",
            field=models.ManyToManyField(
                related_name="sets", to="vocabulary.word", verbose_name="Set words"
            ),
        ),
    ]
