# Generated by Django 4.2.10 on 2024-04-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0003_alter_wordsupdatehistory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="translatorhistorydetails",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Translator history detail",
                "verbose_name_plural": "Translator history details",
            },
        ),
        migrations.AddField(
            model_name="translatorhistorydetails",
            name="verdict",
            field=models.CharField(
                choices=[("C", "Correct"), ("I", "Incorrect"), ("SC", "Semi-correct")],
                default=1,
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
