# Generated by Django 4.2.11 on 2024-05-25 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exercises", "0003_translatorhistorydetails_task_translation_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="translatoruserdefaultsettings",
            name="unique_user_translator_settings",
        ),
        migrations.AlterField(
            model_name="translatoruserdefaultsettings",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translator_settings",
                to=settings.AUTH_USER_MODEL,
                unique=True,
                verbose_name="Пользователь",
            ),
        ),
    ]
