# Generated by Django 4.2.10 on 2024-04-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0004_alter_translatorhistorydetails_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translatorhistorydetails",
            name="answer_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="User answer time"
            ),
        ),
    ]
