# Generated by Django 4.2.11 on 2024-05-25 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "exercises",
            "0004_remove_translatoruserdefaultsettings_unique_user_translator_settings_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="translatoruserdefaultsettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translator_settings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
