# Generated by Django 4.2.11 on 2024-07-06 07:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0005_alter_translatoruserdefaultsettings_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="translatoruserdefaultsettings",
            options={
                "verbose_name": "Translator exercise user default settings",
                "verbose_name_plural": "Translator exercise users default settings",
            },
        ),
        migrations.AlterModelOptions(
            name="wordsupdatehistory",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Word activity status changes history",
                "verbose_name_plural": "Words activity status changes history",
            },
        ),
        migrations.AlterModelTableComment(
            name="exercise",
            table_comment="Exercises with words available in the app",
        ),
        migrations.AlterModelTableComment(
            name="favoriteexercise",
            table_comment="Users favorite exercises",
        ),
        migrations.AlterModelTableComment(
            name="hint",
            table_comment="Hints available to users for use in exercises",
        ),
        migrations.AlterModelTableComment(
            name="translatorhistorydetails",
            table_comment='History details of users passing "Translator" exercise',
        ),
        migrations.AlterModelTableComment(
            name="translatoruserdefaultsettings",
            table_comment="Translator exercise settings which are used by default for the user",
        ),
        migrations.AlterModelTableComment(
            name="usersexerciseshistory",
            table_comment="History details of users passing exercises",
        ),
        migrations.AlterModelTableComment(
            name="wordset",
            table_comment="Sets of words available for the exercise saved by the user for a quick start",
        ),
        migrations.AlterModelTableComment(
            name="wordsupdatehistory",
            table_comment="Words activity status changes history",
        ),
    ]
