# Generated by Django 4.2.10 on 2024-04-22 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0005_alter_translatorhistorydetails_answer_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translatorhistorydetails",
            name="suggested_options",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
