# Generated by Django 4.2.10 on 2024-04-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0006_alter_translatorhistorydetails_suggested_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersexerciseshistory",
            name="complete_time",
            field=models.TimeField(
                blank=True,
                null=True,
                verbose_name="The time in which the exercise was completed",
            ),
        ),
    ]
