# Generated by Django 4.2.11 on 2024-07-11 09:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0002_alter_wordsformgroups_options_and_more"),
        ("exercises", "0006_alter_translatoruserdefaultsettings_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExerciseHistoryDetails",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text_answer", models.CharField(max_length=1024)),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("C", "Correct"),
                            ("I", "Incorrect"),
                            ("SC", "Semi-correct"),
                        ],
                        max_length=2,
                    ),
                ),
                ("suggested_options", models.JSONField(blank=True, null=True)),
                (
                    "answer_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="User answer time"
                    ),
                ),
                (
                    "approach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="exercises.usersexerciseshistory",
                        verbose_name="Approach",
                    ),
                ),
                (
                    "hints_used",
                    models.ManyToManyField(
                        blank=True,
                        related_name="history",
                        to="exercises.hint",
                        verbose_name="Hints used",
                    ),
                ),
                (
                    "task_translation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises_history",
                        to="vocabulary.wordtranslation",
                        verbose_name="Перевод слова",
                    ),
                ),
                (
                    "task_word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises_history",
                        to="vocabulary.word",
                        verbose_name="Слово",
                    ),
                ),
            ],
            options={
                "verbose_name": "Translator history detail",
                "verbose_name_plural": "Translator history details",
                "db_table_comment": 'History details of users passing "Translator" exercise',
                "ordering": ("-created",),
                "get_latest_by": ("created",),
            },
        ),
        migrations.DeleteModel(
            name="TranslatorHistoryDetails",
        ),
    ]
