# Generated by Django 4.2.10 on 2024-04-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0007_usersexerciseshistory_complete_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="translatorhistorydetails",
            name="text_task",
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
