# Generated by Django 4.2.11 on 2024-07-11 09:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0007_exercisehistorydetails_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exercisehistorydetails",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Exercise history detail",
                "verbose_name_plural": "Exercise history details",
            },
        ),
        migrations.AlterModelTableComment(
            name="exercisehistorydetails",
            table_comment="History details of users passing some exercise",
        ),
    ]
