# Generated by Django 4.2.14 on 2024-07-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0008_alter_exercisehistorydetails_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="exercise",
            table_comment="Exercises with user's words",
        ),
        migrations.AlterField(
            model_name="exercise",
            name="available",
            field=models.BooleanField(
                default=False, verbose_name="Is the exercise available for users"
            ),
        ),
    ]
