# Generated by Django 4.2.10 on 2024-04-22 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0001_initial"),
        ("exercises", "0008_translatorhistorydetails_text_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="translatorhistorydetails",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises_history",
                to="languages.language",
                verbose_name="Язык",
            ),
        ),
    ]
