# Generated by Django 4.2.14 on 2024-07-29 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0005_alter_worddefinitions_options_and_more"),
        ("exercises", "0009_alter_exercise_table_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercisehistorydetails",
            name="task_translation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises_history",
                to="vocabulary.wordtranslation",
                verbose_name="Word translation",
            ),
        ),
        migrations.AlterField(
            model_name="wordset",
            name="last_exercise_date",
            field=models.DateTimeField(
                editable=False, null=True, verbose_name="Дата последней тренировки"
            ),
        ),
    ]
