# Generated by Django 4.2.10 on 2024-04-22 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0002_word_last_exercise_date"),
        ("exercises", "0009_translatorhistorydetails_language"),
    ]

    operations = [
        migrations.RenameField(
            model_name="translatorhistorydetails",
            old_name="word",
            new_name="task_word",
        ),
        migrations.RemoveField(
            model_name="translatorhistorydetails",
            name="language",
        ),
        migrations.RemoveField(
            model_name="translatorhistorydetails",
            name="text_task",
        ),
        migrations.AddField(
            model_name="translatorhistorydetails",
            name="task_translation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises_history",
                to="vocabulary.wordtranslation",
                verbose_name="Перевод слова",
            ),
        ),
    ]
