# Generated by Django 4.2.10 on 2024-04-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0010_rename_word_translatorhistorydetails_task_word_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersexerciseshistory",
            name="hints_available",
            field=models.ManyToManyField(
                blank=True,
                related_name="approaches",
                to="exercises.hint",
                verbose_name="Approach available hints",
            ),
        ),
    ]
