# Generated by Django 4.2.10 on 2024-04-23 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0012_alter_translatoruserdefaultsettings_repetitions_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translatoruserdefaultsettings",
            name="mode",
            field=models.CharField(
                choices=[
                    ("FI", "Free input (one translation is enough)"),
                    ("FIM", "Free input (maximum translations quantity)"),
                    ("V", "Choose from variants"),
                ],
                default="FI",
                max_length=32,
                verbose_name="Exercise chosen mode",
            ),
        ),
        migrations.AlterField(
            model_name="usersexerciseshistory",
            name="mode",
            field=models.CharField(
                choices=[
                    ("FI", "Free input (one translation is enough)"),
                    ("FIM", "Free input (maximum translations quantity)"),
                    ("V", "Choose from variants"),
                ],
                default="FI",
                max_length=3,
                verbose_name="Exercise chosen mode",
            ),
        ),
    ]
