# Generated by Django 4.2.11 on 2024-05-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0013_alter_translatoruserdefaultsettings_mode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hint",
            name="code",
            field=models.CharField(
                max_length=32, unique=True, verbose_name="Hint short code"
            ),
        ),
    ]
