# Generated by Django 4.2.15 on 2024-08-31 10:56

import apps.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vocabulary", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date created"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Date modified"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=256, verbose_name="Название упражнения"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=4096, verbose_name="Описание"),
                ),
                (
                    "constraint_description",
                    models.CharField(
                        blank=True, max_length=512, verbose_name="Описание ограничения"
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="exercises/icons/",
                        verbose_name="Иконка упражнения",
                    ),
                ),
                (
                    "available",
                    models.BooleanField(
                        default=False,
                        verbose_name="Упражнение доступно для прохождения пользователями",
                    ),
                ),
            ],
            options={
                "verbose_name": "Упражнение",
                "verbose_name_plural": "Упражнения",
                "db_table_comment": "Упражнение со словами",
                "ordering": ("-created",),
                "get_latest_by": ("created", "modified"),
            },
        ),
        migrations.CreateModel(
            name="Hint",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="Название подсказки"
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=128, verbose_name="Описание подсказки"),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=32,
                        unique=True,
                        verbose_name="Короткий код подсказки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Подсказка",
                "verbose_name_plural": "Подсказки",
                "db_table_comment": "Подсказки досутпные для пользователей в упражнениях",
                "ordering": ("-created",),
                "get_latest_by": ("created",),
            },
        ),
        migrations.CreateModel(
            name="UsersExercisesHistory",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "words_amount",
                    models.IntegerField(
                        verbose_name="Количество слов пройденных в упражнении"
                    ),
                ),
                (
                    "corrects_amount",
                    models.IntegerField(verbose_name="Количество правильных ответов"),
                ),
                (
                    "incorrects_amount",
                    models.IntegerField(verbose_name="Количество неправильных ответов"),
                ),
                (
                    "answer_time_limit",
                    models.TimeField(
                        blank=True,
                        null=True,
                        verbose_name="Установленное ограничение времени",
                    ),
                ),
                (
                    "complete_time",
                    models.TimeField(
                        blank=True,
                        null=True,
                        verbose_name="Время прохождения упражнения",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("FI", "Свободный ввод (одного перевода достаточно)"),
                            ("FIM", "Свободный ввод (максимальное кол-во переводов)"),
                            ("V", "Выбор из вариантов ответа"),
                        ],
                        default="FI",
                        max_length=3,
                        verbose_name="Выбранный режим прохождения упражнения",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users_history",
                        to="exercises.exercise",
                        verbose_name="Упражнение",
                    ),
                ),
                (
                    "hints_available",
                    models.ManyToManyField(
                        blank=True,
                        related_name="approaches",
                        to="exercises.hint",
                        verbose_name="Подсказки доступные в этом подходе",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Прохождение упражнения пользователем",
                "verbose_name_plural": "Прохождения упражнений пользователем",
                "db_table_comment": "История прохождения упражнений пользователем",
                "ordering": ("-created",),
                "get_latest_by": ("created",),
            },
        ),
        migrations.CreateModel(
            name="WordsUpdateHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date created"
                    ),
                ),
                (
                    "activity_status",
                    models.CharField(
                        choices=[("I", "Inactive"), ("A", "Active"), ("M", "Mastered")],
                        default="I",
                        max_length=8,
                        verbose_name="Статус активности",
                    ),
                ),
                (
                    "new_activity_status",
                    models.CharField(
                        choices=[("I", "Inactive"), ("A", "Active"), ("M", "Mastered")],
                        default="A",
                        max_length=8,
                        verbose_name="Статус активности",
                    ),
                ),
                (
                    "approach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="words_updates",
                        to="exercises.usersexerciseshistory",
                        verbose_name="Подход",
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="update_history",
                        to="vocabulary.word",
                        verbose_name="Слово",
                    ),
                ),
            ],
            options={
                "verbose_name": "История изменения статуса активности слова",
                "verbose_name_plural": "История изменения статуса активности слов",
                "db_table_comment": "История изменения статуса активности слов",
                "ordering": ("-created",),
                "get_latest_by": ("created",),
            },
        ),
        migrations.CreateModel(
            name="WordSet",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date created"
                    ),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="Slug")),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64, verbose_name="Название набора слов"
                    ),
                ),
                (
                    "last_exercise_date",
                    models.DateTimeField(
                        editable=False,
                        null=True,
                        verbose_name="Дата последней тренировки",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="word_sets",
                        to="exercises.exercise",
                        verbose_name="Упражнение",
                    ),
                ),
                (
                    "words",
                    models.ManyToManyField(
                        related_name="sets",
                        to="vocabulary.word",
                        verbose_name="Слова набора",
                    ),
                ),
            ],
            options={
                "verbose_name": "Набор слов",
                "verbose_name_plural": "Наборы слов",
                "db_table_comment": "Набор доступных для упражнения слов для быстрого старта",
                "ordering": ("-last_exercise_date", "-created"),
                "get_latest_by": ("created",),
            },
            bases=(apps.core.models.GetObjectBySlugModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="TranslatorUserDefaultSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("FI", "Свободный ввод (одного перевода достаточно)"),
                            ("FIM", "Свободный ввод (максимальное кол-во переводов)"),
                            ("V", "Выбор из вариантов ответа"),
                        ],
                        default="FI",
                        max_length=32,
                        verbose_name="Выбранный режим прохождения упражнения",
                    ),
                ),
                (
                    "answer_time_limit",
                    models.TimeField(
                        blank=True,
                        null=True,
                        verbose_name="Установленное ограничение времени",
                    ),
                ),
                (
                    "repetitions_amount",
                    models.SmallIntegerField(
                        default=1, verbose_name="Количество повторений каждого слова"
                    ),
                ),
                (
                    "from_language",
                    models.CharField(
                        choices=[
                            ("LTN", "С изучаемого языка"),
                            ("NTL", "С родного языка"),
                            ("LTL", "С изучаемого языка на изучаемый"),
                            ("A", "Попеременно"),
                        ],
                        default="LTN",
                        max_length=32,
                        verbose_name="Перевод с изучаемого или родного языка",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translator_settings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки пользователя по умолчанию для упражнения Переводчик",
                "verbose_name_plural": "Настройки пользователей по умолчанию для упражнения Переводчик",
                "db_table_comment": "Настройки для упражнения Переводчик применяемый по умолчанию для пользователя",
            },
        ),
        migrations.CreateModel(
            name="FavoriteExercise",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_for",
                        to="exercises.exercise",
                        verbose_name="Упражнение",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_exercises",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранное упражнение",
                "verbose_name_plural": "Избранные упражнения",
                "db_table_comment": "Избранные упражнения",
                "ordering": ("-created",),
                "get_latest_by": ("created",),
            },
        ),
        migrations.CreateModel(
            name="ExerciseHistoryDetails",
            fields=[
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Date created"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("text_answer", models.CharField(max_length=1024)),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("C", "Правильно"),
                            ("I", "Неправильно"),
                            ("SC", "Почти правильно"),
                        ],
                        max_length=2,
                    ),
                ),
                ("suggested_options", models.JSONField(blank=True, null=True)),
                (
                    "answer_time",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Время ответа пользователя"
                    ),
                ),
                (
                    "approach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="exercises.usersexerciseshistory",
                        verbose_name="Подход",
                    ),
                ),
                (
                    "hints_used",
                    models.ManyToManyField(
                        blank=True,
                        related_name="history",
                        to="exercises.hint",
                        verbose_name="Использованные подсказки",
                    ),
                ),
                (
                    "task_translation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises_history",
                        to="vocabulary.wordtranslation",
                        verbose_name="Перевод слова",
                    ),
                ),
                (
                    "task_word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises_history",
                        to="vocabulary.word",
                        verbose_name="Слово",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пошаговая история прохождения упражнения",
                "verbose_name_plural": "Пошаговая история прохождения упражнений",
                "db_table_comment": "Ответы пользователя в подходе",
                "ordering": ("-created",),
                "get_latest_by": ("created",),
            },
        ),
        migrations.AddField(
            model_name="exercise",
            name="hints_available",
            field=models.ManyToManyField(
                blank=True,
                related_name="exercises",
                to="exercises.hint",
                verbose_name="Подсказки доступные в упражнении",
            ),
        ),
    ]
