# Generated by Django 4.2.15 on 2024-09-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="slug",
            field=models.SlugField(max_length=1024, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="wordset",
            name="slug",
            field=models.SlugField(max_length=1024, unique=True, verbose_name="Slug"),
        ),
    ]
