# Generated by Django 4.2.15 on 2024-09-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exercises", "0002_alter_exercise_slug_alter_wordset_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordsupdatehistory",
            name="new_activity_status",
            field=models.CharField(
                choices=[("I", "Inactive"), ("A", "Active"), ("M", "Mastered")],
                default="A",
                max_length=8,
                verbose_name="New activity status",
            ),
        ),
    ]
