# Generated by Django 4.2.15 on 2024-12-16 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "vocabulary",
            "0018_alter_defaultwordcards_options_alter_wordtag_options_and_more",
        ),
        ("exercises", "0003_alter_wordsupdatehistory_new_activity_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exercise",
            options={
                "get_latest_by": ("created", "modified"),
                "ordering": ("-created",),
                "verbose_name": "Exercise",
                "verbose_name_plural": "Exercises",
            },
        ),
        migrations.AlterModelOptions(
            name="exercisehistorydetails",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Exercise history detail",
                "verbose_name_plural": "Exercise history details",
            },
        ),
        migrations.AlterModelOptions(
            name="favoriteexercise",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Favorite exercise",
                "verbose_name_plural": "Favorite exercises",
            },
        ),
        migrations.AlterModelOptions(
            name="hint",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Hint",
                "verbose_name_plural": "Hints",
            },
        ),
        migrations.AlterModelOptions(
            name="translatoruserdefaultsettings",
            options={
                "verbose_name": "Translator exercise user default settings",
                "verbose_name_plural": "Translator exercise users default settings",
            },
        ),
        migrations.AlterModelOptions(
            name="usersexerciseshistory",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "User exercise approach",
                "verbose_name_plural": "Users exercise approaches",
            },
        ),
        migrations.AlterModelOptions(
            name="wordset",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-last_exercise_date", "-created"),
                "verbose_name": "Word set",
                "verbose_name_plural": "Word sets",
            },
        ),
        migrations.AlterModelOptions(
            name="wordsupdatehistory",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Word activity status changes history",
                "verbose_name_plural": "Words activity status changes history",
            },
        ),
        migrations.AlterModelTableComment(
            name="exercise",
            table_comment="Exercises with user's words",
        ),
        migrations.AlterModelTableComment(
            name="exercisehistorydetails",
            table_comment="History details of users passing some exercise",
        ),
        migrations.AlterModelTableComment(
            name="favoriteexercise",
            table_comment="Users favorite exercises",
        ),
        migrations.AlterModelTableComment(
            name="hint",
            table_comment="Hints available to users for use in exercises",
        ),
        migrations.AlterModelTableComment(
            name="translatoruserdefaultsettings",
            table_comment="Translator exercise settings which are used by default for the user",
        ),
        migrations.AlterModelTableComment(
            name="usersexerciseshistory",
            table_comment="History details of users passing exercises",
        ),
        migrations.AlterModelTableComment(
            name="wordset",
            table_comment="Sets of words available for the exercise saved by the user for a quick start",
        ),
        migrations.AlterModelTableComment(
            name="wordsupdatehistory",
            table_comment="Words activity status changes history",
        ),
        migrations.AlterField(
            model_name="exercise",
            name="available",
            field=models.BooleanField(
                default=False, verbose_name="Is the exercise available for users"
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="constraint_description",
            field=models.CharField(
                blank=True, max_length=512, verbose_name="Constraint description"
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="hints_available",
            field=models.ManyToManyField(
                blank=True,
                related_name="exercises",
                to="exercises.hint",
                verbose_name="Exercise available hints",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="exercises/icons/",
                verbose_name="Exercise icon",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="name",
            field=models.CharField(max_length=256, verbose_name="Exercise name"),
        ),
        migrations.AlterField(
            model_name="exercisehistorydetails",
            name="answer_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="User answer time"
            ),
        ),
        migrations.AlterField(
            model_name="exercisehistorydetails",
            name="approach",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="exercises.usersexerciseshistory",
                verbose_name="Approach",
            ),
        ),
        migrations.AlterField(
            model_name="exercisehistorydetails",
            name="hints_used",
            field=models.ManyToManyField(
                blank=True,
                related_name="history",
                to="exercises.hint",
                verbose_name="Hints used",
            ),
        ),
        migrations.AlterField(
            model_name="exercisehistorydetails",
            name="task_translation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises_history",
                to="vocabulary.wordtranslation",
                verbose_name="Word translation",
            ),
        ),
        migrations.AlterField(
            model_name="exercisehistorydetails",
            name="verdict",
            field=models.CharField(
                choices=[("C", "Correct"), ("I", "Incorrect"), ("SC", "Semi-correct")],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="favoriteexercise",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_for",
                to="exercises.exercise",
                verbose_name="Exercise",
            ),
        ),
        migrations.AlterField(
            model_name="hint",
            name="code",
            field=models.CharField(
                max_length=32, unique=True, verbose_name="Hint short code"
            ),
        ),
        migrations.AlterField(
            model_name="hint",
            name="description",
            field=models.CharField(max_length=128, verbose_name="Hint details"),
        ),
        migrations.AlterField(
            model_name="hint",
            name="name",
            field=models.CharField(
                max_length=32, unique=True, verbose_name="Hint name"
            ),
        ),
        migrations.AlterField(
            model_name="translatoruserdefaultsettings",
            name="answer_time_limit",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Set time limit"
            ),
        ),
        migrations.AlterField(
            model_name="translatoruserdefaultsettings",
            name="from_language",
            field=models.CharField(
                choices=[
                    ("LTN", "From learning"),
                    ("NTL", "From native"),
                    ("LTL", "From learning to learning"),
                    ("A", "Alternately"),
                ],
                default="LTN",
                max_length=32,
                verbose_name="Translate from learning or native language",
            ),
        ),
        migrations.AlterField(
            model_name="translatoruserdefaultsettings",
            name="mode",
            field=models.CharField(
                choices=[
                    ("FI", "Free input (one translation is enough)"),
                    ("FIM", "Free input (maximum translations quantity)"),
                    ("V", "Choose from variants"),
                ],
                default="FI",
                max_length=32,
                verbose_name="Exercise chosen mode",
            ),
        ),
        migrations.AlterField(
            model_name="translatoruserdefaultsettings",
            name="repetitions_amount",
            field=models.SmallIntegerField(
                default=1, verbose_name="Every word repetitions amount"
            ),
        ),
        migrations.AlterField(
            model_name="usersexerciseshistory",
            name="answer_time_limit",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Set time limit"
            ),
        ),
        migrations.AlterField(
            model_name="usersexerciseshistory",
            name="complete_time",
            field=models.TimeField(
                blank=True,
                null=True,
                verbose_name="The time in which the exercise was completed",
            ),
        ),
        migrations.AlterField(
            model_name="usersexerciseshistory",
            name="corrects_amount",
            field=models.IntegerField(verbose_name="Correct answers amount"),
        ),
        migrations.AlterField(
            model_name="usersexerciseshistory",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_history",
                to="exercises.exercise",
                verbose_name="Exercise",
            ),
        ),
        migrations.AlterField(
            model_name="usersexerciseshistory",
            name="hints_available",
            field=models.ManyToManyField(
                blank=True,
                related_name="approaches",
                to="exercises.hint",
                verbose_name="Approach available hints",
            ),
        ),
        migrations.AlterField(
            model_name="usersexerciseshistory",
            name="incorrects_amount",
            field=models.IntegerField(verbose_name="Incorrect answers amount"),
        ),
        migrations.AlterField(
            model_name="usersexerciseshistory",
            name="mode",
            field=models.CharField(
                choices=[
                    ("FI", "Free input (one translation is enough)"),
                    ("FIM", "Free input (maximum translations quantity)"),
                    ("V", "Choose from variants"),
                ],
                default="FI",
                max_length=3,
                verbose_name="Exercise chosen mode",
            ),
        ),
        migrations.AlterField(
            model_name="usersexerciseshistory",
            name="words_amount",
            field=models.IntegerField(verbose_name="Words in exercise amount"),
        ),
        migrations.AlterField(
            model_name="wordset",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="word_sets",
                to="exercises.exercise",
                verbose_name="Exercise",
            ),
        ),
        migrations.AlterField(
            model_name="wordset",
            name="name",
            field=models.CharField(max_length=64, verbose_name="Word set name"),
        ),
        migrations.AlterField(
            model_name="wordset",
            name="words",
            field=models.ManyToManyField(
                related_name="sets", to="vocabulary.word", verbose_name="Set words"
            ),
        ),
        migrations.AlterField(
            model_name="wordsupdatehistory",
            name="approach",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="words_updates",
                to="exercises.usersexerciseshistory",
                verbose_name="Approach",
            ),
        ),
    ]
