# Generated by Django 4.2.15 on 2024-12-16 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0020_alter_antonym_options_alter_collection_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exercises", "0005_alter_exercise_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exercise",
            options={
                "get_latest_by": ("created", "modified"),
                "ordering": ("-created",),
                "verbose_name": "Упражнение",
                "verbose_name_plural": "Упражнения",
            },
        ),
        migrations.AlterModelOptions(
            name="exercisehistorydetails",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Детали прохождения упражнения",
                "verbose_name_plural": "Детали прохождения упражнения",
            },
        ),
        migrations.AlterModelOptions(
            name="favoriteexercise",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Избранное упражнение",
                "verbose_name_plural": "Избранные упражнения",
            },
        ),
        migrations.AlterModelOptions(
            name="hint",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Подсказка",
                "verbose_name_plural": "Подсказки",
            },
        ),
        migrations.AlterModelOptions(
            name="translatoruserdefaultsettings",
            options={
                "verbose_name": "Настройки пользователя по умолчанию для упражнения Переводчик",
                "verbose_name_plural": "Настройки пользователей по умолчанию для упражнения Переводчик",
            },
        ),
        migrations.AlterModelOptions(
            name="usersexerciseshistory",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Подход",
                "verbose_name_plural": "Подходы",
            },
        ),
        migrations.AlterModelOptions(
            name="wordset",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-last_exercise_date", "-created"),
                "verbose_name": "Набор слов",
                "verbose_name_plural": "Наборы слов",
            },
        ),
        migrations.AlterModelOptions(
            name="wordsupdatehistory",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "История изменения статуса активности слова",
                "verbose_name_plural": "История изменения статусов активности слов",
            },
        ),
        migrations.AlterModelTableComment(
            name="exercise",
            table_comment="Упражнения со словами пользователя",
        ),
        migrations.AlterModelTableComment(
            name="exercisehistorydetails",
            table_comment="Детали прохождения упражнений пользователями",
        ),
        migrations.AlterModelTableComment(
            name="favoriteexercise",
            table_comment="Избранные упражнения пользователей",
        ),
        migrations.AlterModelTableComment(
            name="hint",
            table_comment="Доступные для пользователя подсказки в этом упражнении",
        ),
        migrations.AlterModelTableComment(
            name="translatoruserdefaultsettings",
            table_comment="Настройки пользователя по умолчанию для упражнения Переводчик",
        ),
        migrations.AlterModelTableComment(
            name="usersexerciseshistory",
            table_comment="История прохождения упражнений пользователями",
        ),
        migrations.AlterModelTableComment(
            name="wordset",
            table_comment="Наборы слов доступные для упражнения, сохраненные пользователем для быстрого старта",
        ),
        migrations.AlterModelTableComment(
            name="wordsupdatehistory",
            table_comment="История изменения статусов активности слов",
        ),
        migrations.AlterField(
            model_name="exercise",
            name="available",
            field=models.BooleanField(
                default=False,
                verbose_name="Доступно ли упражнение для прохождения пользователями",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="constraint_description",
            field=models.CharField(
                blank=True, max_length=512, verbose_name="Описание ограничения"
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="description",
            field=models.CharField(max_length=4096, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="hints_available",
            field=models.ManyToManyField(
                blank=True,
                related_name="exercises",
                to="exercises.hint",
                verbose_name="Доступные подсказки",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="exercises/icons/",
                verbose_name="Иконка упражнения",
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="name",
            field=models.CharField(max_length=256, verbose_name="Название упражнения"),
        ),
        migrations.AlterField(
            model_name="exercisehistorydetails",
            name="answer_time",
            field=models.TimeField(blank=True, null=True, verbose_name="Время ответа"),
        ),
        migrations.AlterField(
            model_name="exercisehistorydetails",
            name="approach",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="exercises.usersexerciseshistory",
                verbose_name="Подход",
            ),
        ),
        migrations.AlterField(
            model_name="exercisehistorydetails",
            name="hints_used",
            field=models.ManyToManyField(
                blank=True,
                related_name="history",
                to="exercises.hint",
                verbose_name="Использованные подсказки",
            ),
        ),
        migrations.AlterField(
            model_name="exercisehistorydetails",
            name="task_translation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises_history",
                to="vocabulary.wordtranslation",
                verbose_name="Перевод слова",
            ),
        ),
        migrations.AlterField(
            model_name="exercisehistorydetails",
            name="task_word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises_history",
                to="vocabulary.word",
                verbose_name="Слово",
            ),
        ),
        migrations.AlterField(
            model_name="exercisehistorydetails",
            name="verdict",
            field=models.CharField(
                choices=[("C", "Верно"), ("I", "Неверно"), ("SC", "Почти верно")],
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="favoriteexercise",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_for",
                to="exercises.exercise",
                verbose_name="Упражнение",
            ),
        ),
        migrations.AlterField(
            model_name="favoriteexercise",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_exercises",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="hint",
            name="code",
            field=models.CharField(
                max_length=32, unique=True, verbose_name="Короткий код подсказки"
            ),
        ),
        migrations.AlterField(
            model_name="hint",
            name="description",
            field=models.CharField(max_length=128, verbose_name="Описание подсказки"),
        ),
        migrations.AlterField(
            model_name="hint",
            name="name",
            field=models.CharField(
                max_length=32, unique=True, verbose_name="Название подсказки"
            ),
        ),
        migrations.AlterField(
            model_name="translatoruserdefaultsettings",
            name="answer_time_limit",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Настройка ограничения по времени"
            ),
        ),
        migrations.AlterField(
            model_name="translatoruserdefaultsettings",
            name="from_language",
            field=models.CharField(
                choices=[
                    ("LTN", "С изучаемого"),
                    ("NTL", "С родного"),
                    ("LTL", "С изучаемого на другой изучаемый"),
                    ("A", "Поочередно"),
                ],
                default="LTN",
                max_length=32,
                verbose_name="Перевод с изучаемого или родного языка",
            ),
        ),
        migrations.AlterField(
            model_name="translatoruserdefaultsettings",
            name="mode",
            field=models.CharField(
                choices=[
                    ("FI", "Свободный ввод (одного перевода достаточно)"),
                    ("FIM", "Свободный ввод (максимальное количество переводов)"),
                    ("V", "Выбор из вариантов"),
                ],
                default="FI",
                max_length=32,
                verbose_name="Выбранный режим упражнения",
            ),
        ),
        migrations.AlterField(
            model_name="translatoruserdefaultsettings",
            name="repetitions_amount",
            field=models.SmallIntegerField(
                default=1, verbose_name="Количество повторений на каждое слово"
            ),
        ),
        migrations.AlterField(
            model_name="translatoruserdefaultsettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translator_settings",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="usersexerciseshistory",
            name="answer_time_limit",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Настройка ограничения по времени"
            ),
        ),
        migrations.AlterField(
            model_name="usersexerciseshistory",
            name="complete_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Время прохождения упражнения"
            ),
        ),
        migrations.AlterField(
            model_name="usersexerciseshistory",
            name="corrects_amount",
            field=models.IntegerField(verbose_name="Количество правильных ответов"),
        ),
        migrations.AlterField(
            model_name="usersexerciseshistory",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_history",
                to="exercises.exercise",
                verbose_name="Упражнение",
            ),
        ),
        migrations.AlterField(
            model_name="usersexerciseshistory",
            name="hints_available",
            field=models.ManyToManyField(
                blank=True,
                related_name="approaches",
                to="exercises.hint",
                verbose_name="Доступные подсказки в этом подходе",
            ),
        ),
        migrations.AlterField(
            model_name="usersexerciseshistory",
            name="incorrects_amount",
            field=models.IntegerField(verbose_name="Количество неправильных ответов"),
        ),
        migrations.AlterField(
            model_name="usersexerciseshistory",
            name="mode",
            field=models.CharField(
                choices=[
                    ("FI", "Свободный ввод (одного перевода достаточно)"),
                    ("FIM", "Свободный ввод (максимальное количество переводов)"),
                    ("V", "Выбор из вариантов"),
                ],
                default="FI",
                max_length=3,
                verbose_name="Выбранный режим упражнения",
            ),
        ),
        migrations.AlterField(
            model_name="usersexerciseshistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="exercises_history",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="usersexerciseshistory",
            name="words_amount",
            field=models.IntegerField(verbose_name="Количество слов в упражнении"),
        ),
        migrations.AlterField(
            model_name="wordset",
            name="exercise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="word_sets",
                to="exercises.exercise",
                verbose_name="Упражнение",
            ),
        ),
        migrations.AlterField(
            model_name="wordset",
            name="last_exercise_date",
            field=models.DateTimeField(
                editable=False, null=True, verbose_name="Дата последней тренировки"
            ),
        ),
        migrations.AlterField(
            model_name="wordset",
            name="name",
            field=models.CharField(max_length=64, verbose_name="Название набора слов"),
        ),
        migrations.AlterField(
            model_name="wordset",
            name="words",
            field=models.ManyToManyField(
                related_name="sets", to="vocabulary.word", verbose_name="Слова набора"
            ),
        ),
        migrations.AlterField(
            model_name="wordsupdatehistory",
            name="activity_status",
            field=models.CharField(
                choices=[("I", "Inactive"), ("A", "Active"), ("M", "Mastered")],
                default="I",
                max_length=8,
                verbose_name="Статус активности",
            ),
        ),
        migrations.AlterField(
            model_name="wordsupdatehistory",
            name="approach",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="words_updates",
                to="exercises.usersexerciseshistory",
                verbose_name="Подход",
            ),
        ),
        migrations.AlterField(
            model_name="wordsupdatehistory",
            name="new_activity_status",
            field=models.CharField(
                choices=[("I", "Inactive"), ("A", "Active"), ("M", "Mastered")],
                default="A",
                max_length=8,
                verbose_name="Новый статус активности",
            ),
        ),
        migrations.AlterField(
            model_name="wordsupdatehistory",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="update_history",
                to="vocabulary.word",
                verbose_name="Слово",
            ),
        ),
    ]
