"""Константы приложения vocabulary."""

MAX_TYPES_AMOUNT = 3
MAX_TAGS_AMOUNT = 10
MIN_TRANSLATIONS_AMOUNT = 1
MAX_TRANSLATIONS_AMOUNT = 16
MAX_NOTES_AMOUNT = 10
MAX_EXAMPLES_AMOUNT = 10
MAX_DEFINITIONS_AMOUNT = 10
MAX_FORMS_AMOUNT = 10
MAX_SYNONYMS_AMOUNT = 16
MAX_ANTONYMS_AMOUNT = 16
MAX_SIMILARS_AMOUNT = 16

REGEX_WORD_MASK = (
    r'^[A-Za-zА-Яа-я\-\!\?]+[A-Za-zА-Яа-я\-\!\?\ ]*[A-Za-zА-Яа-я\-\!\?]+$'
)
