# Generated by Django 4.2.11 on 2024-07-06 07:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wordsformgroups",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Word form group",
                "verbose_name_plural": "Words form groups",
            },
        ),
        migrations.AlterModelTableComment(
            name="antonym",
            table_comment="Words antonyms",
        ),
        migrations.AlterModelTableComment(
            name="collection",
            table_comment="Users words and phrases collections",
        ),
        migrations.AlterModelTableComment(
            name="definition",
            table_comment="Users words and phrases definitions",
        ),
        migrations.AlterModelTableComment(
            name="favoritecollection",
            table_comment="Users favorite collections",
        ),
        migrations.AlterModelTableComment(
            name="favoriteword",
            table_comment="Users favorite words",
        ),
        migrations.AlterModelTableComment(
            name="form",
            table_comment="Words forms",
        ),
        migrations.AlterModelTableComment(
            name="formsgroup",
            table_comment="Groups of possible word forms in language",
        ),
        migrations.AlterModelTableComment(
            name="imageassociation",
            table_comment="Users words and phrases image-associations",
        ),
        migrations.AlterModelTableComment(
            name="note",
            table_comment="Word notes",
        ),
        migrations.AlterModelTableComment(
            name="quoteassociation",
            table_comment="Users words and phrases quote-associations",
        ),
        migrations.AlterModelTableComment(
            name="similar",
            table_comment="Similar words",
        ),
        migrations.AlterModelTableComment(
            name="synonym",
            table_comment="Words synonyms",
        ),
        migrations.AlterModelTableComment(
            name="tag",
            table_comment="Words and phrases tags",
        ),
        migrations.AlterModelTableComment(
            name="type",
            table_comment="Words and phrases types",
        ),
        migrations.AlterModelTableComment(
            name="usageexample",
            table_comment="Users words and phrases usage examples",
        ),
        migrations.AlterModelTableComment(
            name="word",
            table_comment="Users words and phrases",
        ),
        migrations.AlterModelTableComment(
            name="worddefinitions",
            table_comment="Words and definitions intermediary model",
        ),
        migrations.AlterModelTableComment(
            name="wordimageassociations",
            table_comment="Words and image-associations intermediary model",
        ),
        migrations.AlterModelTableComment(
            name="wordquoteassociations",
            table_comment="Words and quote-associations intermediary model",
        ),
        migrations.AlterModelTableComment(
            name="wordsformgroups",
            table_comment="Words and form groups intermediary model",
        ),
        migrations.AlterModelTableComment(
            name="wordsincollections",
            table_comment="Words and collections intermediary model",
        ),
        migrations.AlterModelTableComment(
            name="wordtranslation",
            table_comment="Users words and phrases translations",
        ),
        migrations.AlterModelTableComment(
            name="wordtranslations",
            table_comment="Words and its translations intermediary model",
        ),
        migrations.AlterModelTableComment(
            name="wordusageexamples",
            table_comment="Words and usage examples intermediary model",
        ),
    ]
