# Generated by Django 4.2.11 on 2024-07-11 19:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0002_alter_wordsformgroups_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imageassociation",
            name="name",
        ),
        migrations.AlterField(
            model_name="definition",
            name="text",
            field=models.CharField(
                help_text="Определение слова или фразы",
                max_length=512,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.RegexValidator(
                        message="Acceptable characters: Latin letters (A-Z, a-z), Cyrillic letters (А-Я, а-я), Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe. Make sure word begin with a letter.",
                        regex="^([A-Za-zА-Яа-яёЁ]+)([A-Za-zА-Яа-я-!?.,:'()ёЁ ]*)$",
                    ),
                ],
                verbose_name="Определение",
            ),
        ),
        migrations.AlterField(
            model_name="definition",
            name="translation",
            field=models.CharField(
                blank=True,
                max_length=512,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.RegexValidator(
                        message="Acceptable characters: Latin letters (A-Z, a-z), Cyrillic letters (А-Я, а-я), Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe. Make sure word begin with a letter.",
                        regex="^([A-Za-zА-Яа-яёЁ]+)([A-Za-zА-Яа-я-!?.,:'()ёЁ ]*)$",
                    ),
                ],
                verbose_name="Перевод определения",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="text",
            field=models.CharField(max_length=512, verbose_name="Текст заметки"),
        ),
        migrations.AlterField(
            model_name="usageexample",
            name="text",
            field=models.CharField(
                help_text="Пример использования слова или фразы",
                max_length=512,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.RegexValidator(
                        message="Acceptable characters: Latin letters (A-Z, a-z), Cyrillic letters (А-Я, а-я), Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe. Make sure word begin with a letter.",
                        regex="^([A-Za-zА-Яа-яёЁ]+)([A-Za-zА-Яа-я-!?.,:'()ёЁ ]*)$",
                    ),
                ],
                verbose_name="Пример использования",
            ),
        ),
        migrations.AlterField(
            model_name="usageexample",
            name="translation",
            field=models.CharField(
                blank=True,
                max_length=512,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.RegexValidator(
                        message="Acceptable characters: Latin letters (A-Z, a-z), Cyrillic letters (А-Я, а-я), Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe. Make sure word begin with a letter.",
                        regex="^([A-Za-zА-Яа-яёЁ]+)([A-Za-zА-Яа-я-!?.,:'()ёЁ ]*)$",
                    ),
                ],
                verbose_name="Перевод примера",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="text",
            field=models.CharField(
                max_length=256,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.RegexValidator(
                        message="Acceptable characters: Latin letters (A-Z, a-z), Cyrillic letters (А-Я, а-я), Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe. Make sure word begin with a letter.",
                        regex="^([A-Za-zА-Яа-яёЁ]+)([A-Za-zА-Яа-я-!?.,:'()ёЁ ]*)$",
                    ),
                ],
                verbose_name="Слово или фраза",
            ),
        ),
        migrations.AlterField(
            model_name="wordtranslation",
            name="text",
            field=models.CharField(
                help_text="Перевод слова или фразы на другой язык",
                max_length=256,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.RegexValidator(
                        message="Acceptable characters: Latin letters (A-Z, a-z), Cyrillic letters (А-Я, а-я), Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe. Make sure word begin with a letter.",
                        regex="^([A-Za-zА-Яа-яёЁ]+)([A-Za-zА-Яа-я-!?.,:'()ёЁ ]*)$",
                    ),
                ],
                verbose_name="Перевод",
            ),
        ),
    ]
