# Generated by Django 4.2.8 on 2023-12-15 19:02

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_alter_antonym_options_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='collection',
            name='unique_user_collection',
        ),
        migrations.RemoveConstraint(
            model_name='definition',
            name='unique_definition_in_user_voc',
        ),
        migrations.RemoveConstraint(
            model_name='formsgroup',
            name='unique_group_name',
        ),
        migrations.RemoveConstraint(
            model_name='usageexample',
            name='unique_word_usage_example_in_user_voc',
        ),
        migrations.RemoveConstraint(
            model_name='word',
            name='unique_words_in_user_voc',
        ),
        migrations.RemoveConstraint(
            model_name='wordtranslation',
            name='unique_word_translation_in_user_voc',
        ),
        migrations.AddConstraint(
            model_name='collection',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), models.F('author'), name='unique_user_collection'),
        ),
        migrations.AddConstraint(
            model_name='definition',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('text'), models.F('author'), name='unique_definition_in_user_voc'),
        ),
        migrations.AddConstraint(
            model_name='formsgroup',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('author'), name='unique_group_name'),
        ),
        migrations.AddConstraint(
            model_name='usageexample',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('text'), models.F('author'), name='unique_word_usage_example_in_user_voc'),
        ),
        migrations.AddConstraint(
            model_name='word',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('text'), models.F('author'), name='unique_words_in_user_voc'),
        ),
        migrations.AddConstraint(
            model_name='wordtranslation',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('text'), models.F('author'), name='unique_word_translation_in_user_voc'),
        ),
    ]
