# Generated by Django 4.2.6 on 2023-11-19 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_alter_antonym_options_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='definition',
            name='unique_definition_in_user_voc',
        ),
        migrations.AddConstraint(
            model_name='definition',
            constraint=models.UniqueConstraint(fields=('text', 'author'), name='unique_definition_in_user_voc', violation_error_message='hi'),
        ),
    ]
