# Generated by Django 4.2.14 on 2024-07-27 16:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "vocabulary",
            "0003_remove_imageassociation_name_alter_definition_text_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="antonym",
            name="unique_antonyms_pair",
        ),
        migrations.RemoveConstraint(
            model_name="form",
            name="unique_forms_pair",
        ),
        migrations.RemoveConstraint(
            model_name="similar",
            name="unique_similars_pair",
        ),
        migrations.RemoveConstraint(
            model_name="synonym",
            name="unique_synonyms_pair",
        ),
    ]
