# Generated by Django 4.2.6 on 2023-11-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_remove_definition_unique_definition_in_user_voc_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usageexample',
            name='unique_word_usage_example_in_user_voc',
        ),
        migrations.AddConstraint(
            model_name='usageexample',
            constraint=models.UniqueConstraint(fields=('text', 'author'), name='unique_word_usage_example_in_user_voc', violation_error_message='hi'),
        ),
    ]
