# Generated by Django 4.2.10 on 2024-04-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0003_alter_collection_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="description",
            field=models.CharField(blank=True, max_length=128, verbose_name="Описание"),
        ),
    ]
