# Generated by Django 4.2.14 on 2024-07-29 06:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0004_remove_antonym_unique_antonyms_pair_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="worddefinitions",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Word definition (intermediary model)",
                "verbose_name_plural": "Word definitions (intermediary model)",
            },
        ),
        migrations.AlterModelOptions(
            name="wordimageassociations",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Word image (intermediary model)",
                "verbose_name_plural": "Words images (intermediary model)",
            },
        ),
        migrations.AlterModelOptions(
            name="wordquoteassociations",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Word quote (intermediary model)",
                "verbose_name_plural": "Words quotes (intermediary model)",
            },
        ),
        migrations.AlterModelOptions(
            name="wordsincollections",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Word in collection (intermediary model)",
                "verbose_name_plural": "Words in collections (intermediary model)",
            },
        ),
        migrations.AlterModelOptions(
            name="wordtranslations",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Word translation (intermediary model)",
                "verbose_name_plural": "Word translations (intermediary model)",
            },
        ),
        migrations.AlterModelOptions(
            name="wordusageexamples",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Word usage example (intermediary model)",
                "verbose_name_plural": "Word usage examples (intermediary model)",
            },
        ),
        migrations.AlterModelTableComment(
            name="formsgroup",
            table_comment="Группы форм существующие в языке",
        ),
        migrations.AlterModelTableComment(
            name="imageassociation",
            table_comment="User's words and phrases image-associations",
        ),
        migrations.AlterModelTableComment(
            name="quoteassociation",
            table_comment="User's words and phrases quote-associations",
        ),
        migrations.AlterModelTableComment(
            name="worddefinitions",
            table_comment="Промежуточная модель для определений и слов",
        ),
        migrations.AlterModelTableComment(
            name="wordimageassociations",
            table_comment="Промежуточная модель для картинок-ассоциаций и слов",
        ),
        migrations.AlterModelTableComment(
            name="wordquoteassociations",
            table_comment="Промежуточная модель для цитат-ассоциаций и слов",
        ),
        migrations.AlterModelTableComment(
            name="wordtranslations",
            table_comment="Промежуточная модель для переводов и слов",
        ),
        migrations.AlterField(
            model_name="formsgroup",
            name="color",
            field=models.CharField(
                blank=True,
                max_length=7,
                validators=[
                    django.core.validators.MinLengthValidator(7),
                    django.core.validators.RegexValidator(
                        message="Color must be in hex format.", regex="^#[\\w]+$"
                    ),
                ],
                verbose_name="Цвет группы",
            ),
        ),
        migrations.AlterField(
            model_name="quoteassociation",
            name="quote_author",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Acceptable characters: Latin letters (A-Z, a-z), Cyrillic letters (А-Я, а-я), Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe. Make sure word begin with a letter.",
                        regex="^([A-Za-zА-Яа-яёЁ]+)([A-Za-zА-Яа-я-!?.,:'()ёЁ ]*)$",
                    )
                ],
                verbose_name="Автор Цитаты",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="last_exercise_date",
            field=models.DateTimeField(
                editable=False, null=True, verbose_name="Дата последней тренировки"
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="words",
                to="vocabulary.tag",
                verbose_name="Теги слова",
            ),
        ),
    ]
