# Generated by Django 4.2.14 on 2024-07-29 09:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0005_alter_worddefinitions_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quoteassociation",
            options={
                "get_latest_by": ("created", "modified"),
                "ordering": ("-created", "-modified"),
                "verbose_name": "Ассоциация-цитата",
                "verbose_name_plural": "Ассоциации-цитаты",
            },
        ),
        migrations.AlterModelOptions(
            name="wordsformgroups",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Word form group (intermediary model)",
                "verbose_name_plural": "Words form groups (intermediary model)",
            },
        ),
        migrations.AlterModelTableComment(
            name="collection",
            table_comment="Collections of words and phrases",
        ),
        migrations.AlterModelTableComment(
            name="definition",
            table_comment="Definitions for words and phrases",
        ),
        migrations.AlterModelTableComment(
            name="imageassociation",
            table_comment="Image-associations for words and phrases",
        ),
        migrations.AlterModelTableComment(
            name="quoteassociation",
            table_comment="Quote-associations for words and phrases",
        ),
        migrations.AlterModelTableComment(
            name="usageexample",
            table_comment="Usage examples for words and phrases",
        ),
        migrations.AlterModelTableComment(
            name="wordsformgroups",
            table_comment="Intermediary model for words and form groups",
        ),
        migrations.AlterModelTableComment(
            name="wordtranslation",
            table_comment="Translations for words and phrases",
        ),
    ]
