# Generated by Django 4.2.8 on 2024-02-25 08:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import languages.models


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0003_alter_language_options_alter_language_isocode_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vocabulary", "0006_alter_collection_slug_alter_formsgroup_slug_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="antonym",
            options={"verbose_name": "Антоним", "verbose_name_plural": "Антонимы"},
        ),
        migrations.AlterModelOptions(
            name="collection",
            options={
                "get_latest_by": ["created", "modified"],
                "ordering": ["-created"],
                "verbose_name": "Коллекция",
                "verbose_name_plural": "Коллекции",
            },
        ),
        migrations.AlterModelOptions(
            name="definition",
            options={
                "get_latest_by": ["created", "modified"],
                "ordering": ["-created"],
                "verbose_name": "Определение",
                "verbose_name_plural": "Определения",
            },
        ),
        migrations.AlterModelOptions(
            name="favoritecollection",
            options={
                "get_latest_by": ["created"],
                "ordering": ["-created"],
                "verbose_name": "Избранная коллекция",
                "verbose_name_plural": "Избранные коллекции",
            },
        ),
        migrations.AlterModelOptions(
            name="favoriteword",
            options={
                "get_latest_by": ["created"],
                "ordering": ["-created"],
                "verbose_name": "Избранное слова",
                "verbose_name_plural": "Избранные слова",
            },
        ),
        migrations.AlterModelOptions(
            name="form",
            options={"verbose_name": "Форма", "verbose_name_plural": "Формы"},
        ),
        migrations.AlterModelOptions(
            name="formsgroup",
            options={
                "ordering": ("-created", "name"),
                "verbose_name": "Forms group",
                "verbose_name_plural": "Группы форм",
            },
        ),
        migrations.AlterModelOptions(
            name="imageassociation",
            options={
                "verbose_name": "Ассоциация-картинка",
                "verbose_name_plural": "Ассоциации-картинки",
            },
        ),
        migrations.AlterModelOptions(
            name="note",
            options={
                "get_latest_by": ["created"],
                "ordering": ["-created"],
                "verbose_name": "Заметка",
                "verbose_name_plural": "Заметки",
            },
        ),
        migrations.AlterModelOptions(
            name="similar",
            options={"verbose_name": "Похожее", "verbose_name_plural": "Похожие"},
        ),
        migrations.AlterModelOptions(
            name="synonym",
            options={
                "get_latest_by": ["created", "modified"],
                "ordering": ["-created"],
                "verbose_name": "Синонимы",
                "verbose_name_plural": "Синонимы",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "Тег", "verbose_name_plural": "Теги"},
        ),
        migrations.AlterModelOptions(
            name="type",
            options={"verbose_name": "Тип", "verbose_name_plural": "Типы"},
        ),
        migrations.AlterModelOptions(
            name="usageexample",
            options={
                "get_latest_by": ["created", "modified"],
                "ordering": ["-created"],
                "verbose_name": "Пример использования",
                "verbose_name_plural": "Примеры использования",
            },
        ),
        migrations.AlterModelOptions(
            name="word",
            options={
                "get_latest_by": ["created", "modified"],
                "ordering": ["-created"],
                "verbose_name": "Слово или фраза",
                "verbose_name_plural": "Слова и фразы",
            },
        ),
        migrations.AlterModelOptions(
            name="worddefinitions",
            options={
                "get_latest_by": ["created"],
                "ordering": ["-created"],
                "verbose_name": "Определение слова",
                "verbose_name_plural": "Определения слов",
            },
        ),
        migrations.AlterModelOptions(
            name="wordsincollections",
            options={
                "get_latest_by": ["created"],
                "ordering": ["-created"],
                "verbose_name": "Слова, добавленные в коллекцию",
                "verbose_name_plural": "Слова, добавленные в коллекцию",
            },
        ),
        migrations.AlterModelOptions(
            name="wordtranslation",
            options={
                "get_latest_by": ["created", "modified"],
                "ordering": ["-created"],
                "verbose_name": "Перевод",
                "verbose_name_plural": "Переводы",
            },
        ),
        migrations.AlterModelOptions(
            name="wordtranslations",
            options={
                "get_latest_by": ["created"],
                "ordering": ["-created"],
                "verbose_name": "Перевод слова",
                "verbose_name_plural": "Переводы слов",
            },
        ),
        migrations.AlterModelOptions(
            name="wordusageexamples",
            options={
                "get_latest_by": ["created"],
                "ordering": ["-created"],
                "verbose_name": "Пример использования слова",
                "verbose_name_plural": "Примеры использования слов",
            },
        ),
        migrations.AlterField(
            model_name="collection",
            name="description",
            field=models.TextField(blank=True, max_length=512, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="collection",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Слаг"),
        ),
        migrations.AlterField(
            model_name="collection",
            name="title",
            field=models.CharField(
                max_length=32,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.RegexValidator(
                        message="Acceptable characters: Latin letters (A-Z, a-z), Cyrillic letters (А-Я, а-я), Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe. Make sure word begin with a letter.",
                        regex="^([A-Za-zА-Яа-яёЁ]+)([A-Za-zА-Яа-я-!?.,:'()ёЁ ]*)$",
                    ),
                ],
                verbose_name="Название коллекции",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="words",
            field=models.ManyToManyField(
                blank=True,
                related_name="collections",
                through="vocabulary.WordsInCollections",
                to="vocabulary.word",
                verbose_name="Слово, добавленное в коллекцию",
            ),
        ),
        migrations.AlterField(
            model_name="definition",
            name="text",
            field=models.CharField(
                help_text="Определение слова или фразы",
                max_length=1024,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.RegexValidator(
                        message="Acceptable characters: Latin letters (A-Z, a-z), Cyrillic letters (А-Я, а-я), Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe. Make sure word begin with a letter.",
                        regex="^([A-Za-zА-Яа-яёЁ]+)([A-Za-zА-Яа-я-!?.,:'()ёЁ ]*)$",
                    ),
                ],
                verbose_name="Определение",
            ),
        ),
        migrations.AlterField(
            model_name="definition",
            name="translation",
            field=models.CharField(
                blank=True,
                max_length=1024,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.RegexValidator(
                        message="Acceptable characters: Latin letters (A-Z, a-z), Cyrillic letters (А-Я, а-я), Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe. Make sure word begin with a letter.",
                        regex="^([A-Za-zА-Яа-яёЁ]+)([A-Za-zА-Яа-я-!?.,:'()ёЁ ]*)$",
                    ),
                ],
                verbose_name="Перевод определения",
            ),
        ),
        migrations.AlterField(
            model_name="favoritecollection",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_for",
                to="vocabulary.collection",
                verbose_name="Коллекция",
            ),
        ),
        migrations.AlterField(
            model_name="favoriteword",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_for",
                to="vocabulary.word",
                verbose_name="Слово",
            ),
        ),
        migrations.AlterField(
            model_name="formsgroup",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Слаг"),
        ),
        migrations.AlterField(
            model_name="imageassociation",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Ассоциация-картинка",
                null=True,
                upload_to="words/associations/images",
                verbose_name="Картинка",
            ),
        ),
        migrations.AlterField(
            model_name="imageassociation",
            name="name",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Acceptable characters: Latin letters (A-Z, a-z), Cyrillic letters (А-Я, а-я), Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe. Make sure word begin with a letter.",
                        regex="^([A-Za-zА-Яа-яёЁ]+)([A-Za-zА-Яа-я-!?.,:'()ёЁ ]*)$",
                    )
                ],
                verbose_name="Название для картинки",
            ),
        ),
        migrations.AlterField(
            model_name="imageassociation",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="vocabulary.word",
                verbose_name="Слово",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="text",
            field=models.CharField(max_length=4096, verbose_name="Текст заметки"),
        ),
        migrations.AlterField(
            model_name="note",
            name="word",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="vocabulary.word",
                verbose_name="Слово",
            ),
        ),
        migrations.AlterField(
            model_name="synonym",
            name="difference",
            field=models.CharField(
                blank=True,
                help_text="Разница между %(class)ss",
                max_length=512,
                verbose_name="Разница в использовании",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=32,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.RegexValidator(
                        message="Acceptable characters: Latin letters (A-Z, a-z), Cyrillic letters (А-Я, а-я), Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe. Make sure word begin with a letter.",
                        regex="^([A-Za-zА-Яа-яёЁ]+)([A-Za-zА-Яа-я-!?.,:'()ёЁ ]*)$",
                    ),
                ],
                verbose_name="Имя тега",
            ),
        ),
        migrations.AlterField(
            model_name="type",
            name="name",
            field=models.CharField(
                max_length=64,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.RegexValidator(
                        message="Acceptable characters: Latin letters (A-Z, a-z), Cyrillic letters (А-Я, а-я), Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe. Make sure word begin with a letter.",
                        regex="^([A-Za-zА-Яа-яёЁ]+)([A-Za-zА-Яа-я-!?.,:'()ёЁ ]*)$",
                    ),
                ],
                verbose_name="Имя типа",
            ),
        ),
        migrations.AlterField(
            model_name="type",
            name="name_en",
            field=models.CharField(
                max_length=64,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.RegexValidator(
                        message="Acceptable characters: Latin letters (A-Z, a-z), Cyrillic letters (А-Я, а-я), Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe. Make sure word begin with a letter.",
                        regex="^([A-Za-zА-Яа-яёЁ]+)([A-Za-zА-Яа-я-!?.,:'()ёЁ ]*)$",
                    ),
                ],
                verbose_name="Имя типа",
            ),
        ),
        migrations.AlterField(
            model_name="type",
            name="name_ru",
            field=models.CharField(
                max_length=64,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.RegexValidator(
                        message="Acceptable characters: Latin letters (A-Z, a-z), Cyrillic letters (А-Я, а-я), Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe. Make sure word begin with a letter.",
                        regex="^([A-Za-zА-Яа-яёЁ]+)([A-Za-zА-Яа-я-!?.,:'()ёЁ ]*)$",
                    ),
                ],
                verbose_name="Имя типа",
            ),
        ),
        migrations.AlterField(
            model_name="type",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Слаг"),
        ),
        migrations.AlterField(
            model_name="usageexample",
            name="text",
            field=models.CharField(
                help_text="Пример использования слова или фразы",
                max_length=1024,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.RegexValidator(
                        message="Acceptable characters: Latin letters (A-Z, a-z), Cyrillic letters (А-Я, а-я), Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe. Make sure word begin with a letter.",
                        regex="^([A-Za-zА-Яа-яёЁ]+)([A-Za-zА-Яа-я-!?.,:'()ёЁ ]*)$",
                    ),
                ],
                verbose_name="Пример использования",
            ),
        ),
        migrations.AlterField(
            model_name="usageexample",
            name="translation",
            field=models.CharField(
                blank=True,
                max_length=1024,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    django.core.validators.RegexValidator(
                        message="Acceptable characters: Latin letters (A-Z, a-z), Cyrillic letters (А-Я, а-я), Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe. Make sure word begin with a letter.",
                        regex="^([A-Za-zА-Яа-яёЁ]+)([A-Za-zА-Яа-я-!?.,:'()ёЁ ]*)$",
                    ),
                ],
                verbose_name="Перевод примера",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="activity",
            field=models.CharField(
                choices=[("I", "Неактивное"), ("A", "Активное"), ("M", "Усвоенное")],
                default="I",
                max_length=8,
                verbose_name="Статус активности",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="antonyms",
            field=models.ManyToManyField(
                blank=True,
                help_text="Слова с обратным значением",
                through="vocabulary.Antonym",
                to="vocabulary.word",
                verbose_name="Антонимы",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vocabulary",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="definitions",
            field=models.ManyToManyField(
                blank=True,
                related_name="definition_for",
                through="vocabulary.WordDefinitions",
                to="vocabulary.definition",
                verbose_name="Определения",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="examples",
            field=models.ManyToManyField(
                blank=True,
                related_name="usage_example_for",
                through="vocabulary.WordUsageExamples",
                to="vocabulary.usageexample",
                verbose_name="Пример использования",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="forms",
            field=models.ManyToManyField(
                blank=True,
                help_text="Формы слов",
                through="vocabulary.Form",
                to="vocabulary.word",
                verbose_name="Формы",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="is_problematic",
            field=models.BooleanField(
                default=False, verbose_name="Проблемно ли для вас это слово"
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="language",
            field=models.ForeignKey(
                default=languages.models.Language.get_default_pk,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="words",
                to="languages.language",
                verbose_name="Язык",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="similars",
            field=models.ManyToManyField(
                blank=True,
                help_text="Слова с похожим произношением или написанием",
                through="vocabulary.Similar",
                to="vocabulary.word",
                verbose_name="Похожие",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Слаг"),
        ),
        migrations.AlterField(
            model_name="word",
            name="synonyms",
            field=models.ManyToManyField(
                blank=True,
                help_text="Слова с похожим значением",
                through="vocabulary.Synonym",
                to="vocabulary.word",
                verbose_name="Синонимы",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="words",
                to="vocabulary.tag",
                verbose_name="Теги слов",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="text",
            field=models.CharField(
                max_length=512,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.RegexValidator(
                        message="Acceptable characters: Latin letters (A-Z, a-z), Cyrillic letters (А-Я, а-я), Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe. Make sure word begin with a letter.",
                        regex="^([A-Za-zА-Яа-яёЁ]+)([A-Za-zА-Яа-я-!?.,:'()ёЁ ]*)$",
                    ),
                ],
                verbose_name="Слово или фраза",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="translations",
            field=models.ManyToManyField(
                blank=True,
                related_name="translation_for",
                through="vocabulary.WordTranslations",
                to="vocabulary.wordtranslation",
                verbose_name="Переводы",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="types",
            field=models.ManyToManyField(
                blank=True,
                related_name="words",
                to="vocabulary.type",
                verbose_name="Тип",
            ),
        ),
        migrations.AlterField(
            model_name="worddefinitions",
            name="definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="vocabulary.definition",
                verbose_name="Определение",
            ),
        ),
        migrations.AlterField(
            model_name="worddefinitions",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="vocabulary.word",
                verbose_name="Слово",
            ),
        ),
        migrations.AlterField(
            model_name="wordsformgroups",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="vocabulary.word",
                verbose_name="Слово",
            ),
        ),
        migrations.AlterField(
            model_name="wordsincollections",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="vocabulary.collection",
                verbose_name="Коллекция",
            ),
        ),
        migrations.AlterField(
            model_name="wordsincollections",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="vocabulary.word",
                verbose_name="Слово",
            ),
        ),
        migrations.AlterField(
            model_name="wordtranslation",
            name="language",
            field=models.ForeignKey(
                default=languages.models.Language.get_default_pk,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="words_translations",
                to="languages.language",
                verbose_name="Язык",
            ),
        ),
        migrations.AlterField(
            model_name="wordtranslation",
            name="text",
            field=models.CharField(
                help_text="Перевод слова или фразы на другой язык",
                max_length=512,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.RegexValidator(
                        message="Acceptable characters: Latin letters (A-Z, a-z), Cyrillic letters (А-Я, а-я), Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe. Make sure word begin with a letter.",
                        regex="^([A-Za-zА-Яа-яёЁ]+)([A-Za-zА-Яа-я-!?.,:'()ёЁ ]*)$",
                    ),
                ],
                verbose_name="Перевод",
            ),
        ),
        migrations.AlterField(
            model_name="wordtranslations",
            name="translation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="vocabulary.wordtranslation",
                verbose_name="Перевод",
            ),
        ),
        migrations.AlterField(
            model_name="wordtranslations",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="vocabulary.word",
                verbose_name="Слово",
            ),
        ),
        migrations.AlterField(
            model_name="wordusageexamples",
            name="example",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="vocabulary.usageexample",
                verbose_name="Пример использования",
            ),
        ),
        migrations.AlterField(
            model_name="wordusageexamples",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="vocabulary.word",
                verbose_name="Слово",
            ),
        ),
    ]
