# Generated by Django 4.2.14 on 2024-07-29 09:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0006_alter_quoteassociation_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="formsgroup",
            options={
                "get_latest_by": ("created", "modified"),
                "ordering": ("-created", "-modified", "name"),
                "verbose_name": "Группа форм",
                "verbose_name_plural": "Группы форм",
            },
        ),
        migrations.AlterModelOptions(
            name="imageassociation",
            options={
                "get_latest_by": ("created", "modified"),
                "ordering": ("-created", "-modified"),
                "verbose_name": "Image-association",
                "verbose_name_plural": "Image-associations",
            },
        ),
        migrations.AlterModelOptions(
            name="quoteassociation",
            options={
                "get_latest_by": ("created", "modified"),
                "ordering": ("-created", "-modified"),
                "verbose_name": "Quote-association",
                "verbose_name_plural": "Quote-associations",
            },
        ),
        migrations.AlterModelOptions(
            name="worddefinitions",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Определение слова (промежуточная модель)",
                "verbose_name_plural": "Определения слов (промежуточная модель)",
            },
        ),
        migrations.AlterModelOptions(
            name="wordimageassociations",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Картинка слова (промежуточная модель)",
                "verbose_name_plural": "Картинки слов (промежуточная модель)",
            },
        ),
        migrations.AlterModelOptions(
            name="wordquoteassociations",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Цитата слова (промежуточная модель)",
                "verbose_name_plural": "Цитаты слов (промежуточная модель)",
            },
        ),
        migrations.AlterModelOptions(
            name="wordsformgroups",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Группа форм слова (промежуточная модель)",
                "verbose_name_plural": "Группы форм слов (промежуточная модель)",
            },
        ),
        migrations.AlterModelOptions(
            name="wordsincollections",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Слово, добавленное в коллекцию (промежуточная модель)",
                "verbose_name_plural": "Слова, добавленные в коллекции (промежуточная модель)",
            },
        ),
        migrations.AlterModelOptions(
            name="wordtranslations",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Перевод слова (промежуточная модель)",
                "verbose_name_plural": "Переводы слов (промежуточная модель)",
            },
        ),
        migrations.AlterModelOptions(
            name="wordusageexamples",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Пример использования слова (промежуточная модель)",
                "verbose_name_plural": "Примеры использования слов (промежуточная модель)",
            },
        ),
        migrations.AlterModelTableComment(
            name="antonym",
            table_comment="Слова-антонимы",
        ),
        migrations.AlterModelTableComment(
            name="collection",
            table_comment="Коллекции слов и фраз",
        ),
        migrations.AlterModelTableComment(
            name="definition",
            table_comment="Определения слов и фраз",
        ),
        migrations.AlterModelTableComment(
            name="favoritecollection",
            table_comment="Избранные коллекции",
        ),
        migrations.AlterModelTableComment(
            name="favoriteword",
            table_comment="Избранные слова",
        ),
        migrations.AlterModelTableComment(
            name="form",
            table_comment="Слова-формы",
        ),
        migrations.AlterModelTableComment(
            name="imageassociation",
            table_comment="Картинки-ассоциации слов и фраз",
        ),
        migrations.AlterModelTableComment(
            name="note",
            table_comment="Заметки слова",
        ),
        migrations.AlterModelTableComment(
            name="quoteassociation",
            table_comment="Цитаты-ассоциации слов и фраз",
        ),
        migrations.AlterModelTableComment(
            name="similar",
            table_comment="Похожие слова",
        ),
        migrations.AlterModelTableComment(
            name="synonym",
            table_comment="Слова-синонимы",
        ),
        migrations.AlterModelTableComment(
            name="tag",
            table_comment="Теги слов и фраз",
        ),
        migrations.AlterModelTableComment(
            name="type",
            table_comment="Типы слов и фраз",
        ),
        migrations.AlterModelTableComment(
            name="usageexample",
            table_comment="Примеры использования слов и фраз",
        ),
        migrations.AlterModelTableComment(
            name="word",
            table_comment="Добавленные пользователями слова и фразы",
        ),
        migrations.AlterModelTableComment(
            name="wordsformgroups",
            table_comment="Промежуточная модель для слов и групп форм",
        ),
        migrations.AlterModelTableComment(
            name="wordsincollections",
            table_comment="Промежуточная модель для слов и коллекций",
        ),
        migrations.AlterModelTableComment(
            name="wordtranslation",
            table_comment="Переводы слов и фраз",
        ),
        migrations.AlterModelTableComment(
            name="wordusageexamples",
            table_comment="Промежуточная модель для примеров использования и слов",
        ),
        migrations.AlterField(
            model_name="formsgroup",
            name="name",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.RegexValidator(
                        message="Acceptable characters: Latin letters (A-Z, a-z), Cyrillic letters (А-Я, а-я), Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe. Make sure word begin with a letter.",
                        regex="^([A-Za-zА-Яа-яёЁ]+)([A-Za-zА-Яа-я-!?.,:'()ёЁ ]*)$",
                    ),
                ],
                verbose_name="Название группы",
            ),
        ),
        migrations.AlterField(
            model_name="formsgroup",
            name="translation",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.RegexValidator(
                        message="Acceptable characters: Latin letters (A-Z, a-z), Cyrillic letters (А-Я, а-я), Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe. Make sure word begin with a letter.",
                        regex="^([A-Za-zА-Яа-яёЁ]+)([A-Za-zА-Яа-я-!?.,:'()ёЁ ]*)$",
                    ),
                ],
                verbose_name="Перевод названия группы",
            ),
        ),
        migrations.AlterField(
            model_name="quoteassociation",
            name="text",
            field=models.CharField(
                max_length=256,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Acceptable characters: Latin letters (A-Z, a-z), Cyrillic letters (А-Я, а-я), Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe. Make sure word begin with a letter.",
                        regex="^([A-Za-zА-Яа-яёЁ]+)([A-Za-zА-Яа-я-!?.,:'()ёЁ ]*)$",
                    )
                ],
                verbose_name="Текст цитаты",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="forms_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="words",
                through="vocabulary.WordsFormGroups",
                to="vocabulary.formsgroup",
                verbose_name="Группа форм слова",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="quotes_associations",
            field=models.ManyToManyField(
                blank=True,
                related_name="words",
                through="vocabulary.WordQuoteAssociations",
                to="vocabulary.quoteassociation",
                verbose_name="Ассоциация-цитата",
            ),
        ),
        migrations.AlterField(
            model_name="wordquoteassociations",
            name="quote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="vocabulary.quoteassociation",
                verbose_name="Ассоциация-цитата",
            ),
        ),
        migrations.AlterField(
            model_name="wordsformgroups",
            name="forms_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s",
                to="vocabulary.formsgroup",
                verbose_name="Группа форм",
            ),
        ),
    ]
