# Generated by Django 4.2.8 on 2024-02-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0007_alter_antonym_options_alter_collection_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="examples",
            field=models.ManyToManyField(
                blank=True,
                related_name="example_for",
                through="vocabulary.WordUsageExamples",
                to="vocabulary.usageexample",
                verbose_name="Пример использования",
            ),
        ),
    ]
