# Generated by Django 4.2.14 on 2024-07-29 09:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0007_alter_formsgroup_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="imageassociation",
            options={
                "get_latest_by": ("created", "modified"),
                "ordering": ("-created", "-modified"),
                "verbose_name": "Картинка-ассоциация",
                "verbose_name_plural": "Картинки-ассоциации",
            },
        ),
        migrations.AlterModelOptions(
            name="quoteassociation",
            options={
                "get_latest_by": ("created", "modified"),
                "ordering": ("-created", "-modified"),
                "verbose_name": "Цитата-ассоциация",
                "verbose_name_plural": "Цитаты-ассоциации",
            },
        ),
        migrations.AlterModelOptions(
            name="wordimageassociations",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Картинка-ассоциация слова (промежуточная модель)",
                "verbose_name_plural": "Картинки-ассоциации слов (промежуточная модель)",
            },
        ),
        migrations.AlterModelOptions(
            name="wordquoteassociations",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Цитата-ассоциация слова (промежуточная модель)",
                "verbose_name_plural": "Цитаты-ассоциации слов (промежуточная модель)",
            },
        ),
    ]
