# Generated by Django 4.2.14 on 2024-08-19 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0009_alter_languageimage_options"),
        ("vocabulary", "0009_alter_similar_options_alter_word_similars"),
    ]

    operations = [
        migrations.RenameField(
            model_name="word",
            old_name="forms_groups",
            new_name="form_groups",
        ),
        migrations.AlterField(
            model_name="formsgroup",
            name="language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="form_groups",
                to="languages.language",
                verbose_name="Язык",
            ),
        ),
    ]
