# Generated by Django 4.2.8 on 2024-02-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0009_note_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="antonym",
            options={
                "get_latest_by": ["created", "modified"],
                "ordering": ["-created"],
                "verbose_name": "Антоним",
                "verbose_name_plural": "Антонимы",
            },
        ),
        migrations.AlterModelOptions(
            name="form",
            options={
                "get_latest_by": ["created"],
                "ordering": ["-created"],
                "verbose_name": "Форма",
                "verbose_name_plural": "Формы",
            },
        ),
        migrations.AlterModelOptions(
            name="similar",
            options={
                "get_latest_by": ["created"],
                "ordering": ["-created"],
                "verbose_name": "Похожее",
                "verbose_name_plural": "Похожие",
            },
        ),
        migrations.RemoveConstraint(
            model_name="antonym",
            name="unique_antonym_pair",
        ),
        migrations.RemoveConstraint(
            model_name="form",
            name="unique_forms",
        ),
        migrations.RemoveConstraint(
            model_name="similar",
            name="unique_similars",
        ),
        migrations.RemoveConstraint(
            model_name="synonym",
            name="unique_synonym_pair",
        ),
        migrations.AddField(
            model_name="antonym",
            name="difference",
            field=models.CharField(
                blank=True,
                help_text="Разница между %(class)ss",
                max_length=512,
                verbose_name="Разница в использовании",
            ),
        ),
        migrations.AddField(
            model_name="antonym",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Date modified"
            ),
        ),
        migrations.AddConstraint(
            model_name="antonym",
            constraint=models.CheckConstraint(
                check=models.Q(("to_word", models.F("from_word")), _negated=True),
                name="antonym_not_same_word",
            ),
        ),
        migrations.AddConstraint(
            model_name="antonym",
            constraint=models.UniqueConstraint(
                fields=("from_word", "to_word"), name="unique_antonyms_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="form",
            constraint=models.CheckConstraint(
                check=models.Q(("to_word", models.F("from_word")), _negated=True),
                name="form_not_same_word",
            ),
        ),
        migrations.AddConstraint(
            model_name="form",
            constraint=models.UniqueConstraint(
                fields=("from_word", "to_word"), name="unique_forms_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="similar",
            constraint=models.CheckConstraint(
                check=models.Q(("to_word", models.F("from_word")), _negated=True),
                name="similar_not_same_word",
            ),
        ),
        migrations.AddConstraint(
            model_name="similar",
            constraint=models.UniqueConstraint(
                fields=("from_word", "to_word"), name="unique_similars_pair"
            ),
        ),
        migrations.AddConstraint(
            model_name="synonym",
            constraint=models.CheckConstraint(
                check=models.Q(("to_word", models.F("from_word")), _negated=True),
                name="synonym_not_same_word",
            ),
        ),
        migrations.AddConstraint(
            model_name="synonym",
            constraint=models.UniqueConstraint(
                fields=("from_word", "to_word"), name="unique_synonyms_pair"
            ),
        ),
    ]
