# Generated by Django 4.2.7 on 2023-11-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0010_alter_collection_words_alter_type_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wordsincollections',
            options={'get_latest_by': ['created'], 'ordering': ['-created'], 'verbose_name': 'Слова, добавленные в коллекцию', 'verbose_name_plural': 'Слова, добавленные в коллекцию'},
        ),
        migrations.AlterField(
            model_name='collection',
            name='words',
            field=models.ManyToManyField(blank=True, related_name='collections', through='vocabulary.WordsInCollections', to='vocabulary.word', verbose_name='Слово, добавленное в коллекцию'),
        ),
    ]
