# Generated by Django 4.2.8 on 2024-02-27 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0010_alter_antonym_options_alter_form_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="antonym",
            name="difference",
        ),
        migrations.RemoveField(
            model_name="synonym",
            name="difference",
        ),
        migrations.AddField(
            model_name="antonym",
            name="note",
            field=models.CharField(
                blank=True,
                help_text="Note for %(class)ss",
                max_length=512,
                verbose_name="Заметка",
            ),
        ),
        migrations.AddField(
            model_name="synonym",
            name="note",
            field=models.CharField(
                blank=True,
                help_text="Note for %(class)ss",
                max_length=512,
                verbose_name="Заметка",
            ),
        ),
    ]
