# Generated by Django 4.2.14 on 2024-08-26 08:40

from django.db import migrations, models
import vocabulary.models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0010_rename_forms_groups_word_form_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageassociation",
            name="image",
            field=models.ImageField(
                upload_to=vocabulary.models.image_associations_path,
                verbose_name="Картинка",
            ),
        ),
    ]
