# Generated by Django 4.2.8 on 2024-03-02 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "vocabulary",
            "0011_remove_antonym_difference_remove_synonym_difference_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="antonym",
            name="author",
        ),
        migrations.RemoveField(
            model_name="form",
            name="author",
        ),
        migrations.RemoveField(
            model_name="similar",
            name="author",
        ),
        migrations.RemoveField(
            model_name="synonym",
            name="author",
        ),
    ]
