# Generated by Django 4.2.8 on 2024-03-02 17:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import languages.models


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0003_alter_language_options_alter_language_isocode_and_more"),
        ("vocabulary", "0012_remove_antonym_author_remove_form_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="formsgroup",
            name="color",
            field=models.CharField(
                blank=True,
                max_length=7,
                validators=[
                    django.core.validators.MinLengthValidator(7),
                    django.core.validators.RegexValidator(
                        message="Color must be in hex format.", regex="^#[\\w]+$"
                    ),
                ],
                verbose_name="Group color",
            ),
        ),
        migrations.AddField(
            model_name="formsgroup",
            name="language",
            field=models.ForeignKey(
                default=languages.models.Language.get_default_pk,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="forms_groups",
                to="languages.language",
                verbose_name="Язык",
            ),
        ),
        migrations.AddField(
            model_name="formsgroup",
            name="translation",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    django.core.validators.RegexValidator(
                        message="Acceptable characters: Latin letters (A-Z, a-z), Cyrillic letters (А-Я, а-я), Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe. Make sure word begin with a letter.",
                        regex="^([A-Za-zА-Яа-яёЁ]+)([A-Za-zА-Яа-я-!?.,:'()ёЁ ]*)$",
                    ),
                ],
                verbose_name="Group name translation",
            ),
        ),
    ]
