# Generated by Django 4.2.8 on 2024-03-03 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vocabulary", "0013_formsgroup_color_formsgroup_language_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="antonym",
            options={
                "get_latest_by": ["created"],
                "ordering": ["-created"],
                "verbose_name": "Антоним",
                "verbose_name_plural": "Антонимы",
            },
        ),
        migrations.AlterModelOptions(
            name="collection",
            options={
                "get_latest_by": ["created", "modified"],
                "ordering": ["-created", "-modified"],
                "verbose_name": "Коллекция",
                "verbose_name_plural": "Коллекции",
            },
        ),
        migrations.AlterModelOptions(
            name="definition",
            options={
                "get_latest_by": ["created", "modified"],
                "ordering": ["-created", "-modified"],
                "verbose_name": "Определение",
                "verbose_name_plural": "Определения",
            },
        ),
        migrations.AlterModelOptions(
            name="formsgroup",
            options={
                "get_latest_by": ["created", "modified"],
                "ordering": ("-created", "name"),
                "verbose_name": "Forms group",
                "verbose_name_plural": "Группы форм",
            },
        ),
        migrations.AlterModelOptions(
            name="synonym",
            options={
                "get_latest_by": ["created"],
                "ordering": ["-created"],
                "verbose_name": "Синонимы",
                "verbose_name_plural": "Синонимы",
            },
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={
                "get_latest_by": ["created", "modified"],
                "ordering": ["-created", "-modified"],
                "verbose_name": "Тег",
                "verbose_name_plural": "Теги",
            },
        ),
        migrations.AlterModelOptions(
            name="type",
            options={
                "get_latest_by": ["created", "modified"],
                "ordering": ["-created", "-modified"],
                "verbose_name": "Тип",
                "verbose_name_plural": "Типы",
            },
        ),
        migrations.AlterModelOptions(
            name="usageexample",
            options={
                "get_latest_by": ["created", "modified"],
                "ordering": ["-created", "-modified"],
                "verbose_name": "Пример использования",
                "verbose_name_plural": "Примеры использования",
            },
        ),
        migrations.AlterModelOptions(
            name="word",
            options={
                "get_latest_by": ["created", "modified"],
                "ordering": ["-created", "-modified"],
                "verbose_name": "Слово или фраза",
                "verbose_name_plural": "Слова и фразы",
            },
        ),
        migrations.AlterModelOptions(
            name="wordtranslation",
            options={
                "get_latest_by": ["created", "modified"],
                "ordering": ["-created", "-modified"],
                "verbose_name": "Перевод",
                "verbose_name_plural": "Переводы",
            },
        ),
        migrations.RemoveField(
            model_name="antonym",
            name="modified",
        ),
        migrations.RemoveField(
            model_name="synonym",
            name="modified",
        ),
        migrations.AddField(
            model_name="definition",
            name="slug",
            field=models.SlugField(default="slug", unique=True, verbose_name="Слаг"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="note",
            name="slug",
            field=models.SlugField(default="slug", unique=True, verbose_name="Слаг"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Date created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Date modified"
            ),
        ),
        migrations.AddField(
            model_name="type",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="type",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Date created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="type",
            name="modified",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Date modified"
            ),
        ),
        migrations.AddField(
            model_name="usageexample",
            name="slug",
            field=models.SlugField(default="slug", unique=True, verbose_name="Слаг"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wordtranslation",
            name="slug",
            field=models.SlugField(default="slug", unique=True, verbose_name="Слаг"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="word",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
    ]
