# Generated by Django 4.2.8 on 2024-03-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0014_alter_antonym_options_alter_collection_options_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="favoritecollection",
            constraint=models.UniqueConstraint(
                fields=("collection", "user"), name="unique_user_favorite_collection"
            ),
        ),
        migrations.AddConstraint(
            model_name="favoriteword",
            constraint=models.UniqueConstraint(
                fields=("word", "user"), name="unique_user_favorite_word"
            ),
        ),
        migrations.AddConstraint(
            model_name="note",
            constraint=models.UniqueConstraint(
                fields=("word", "text"), name="unique_word_note"
            ),
        ),
    ]
