# Generated by Django 4.2.15 on 2024-09-01 15:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "languages",
            "0002_userlearninglanguage_user_usernativelanguage_user_and_more",
        ),
        ("vocabulary", "0002_imageassociation_image_url_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FormsGroup",
            new_name="FormGroup",
        ),
    ]
