# Generated by Django 4.2.15 on 2024-08-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0002_alter_collection_author_alter_definition_author_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="defaultwordcards",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "User default word cards type setting",
                "verbose_name_plural": "User default word cards type settings",
            },
        ),
        migrations.AlterModelTableComment(
            name="defaultwordcards",
            table_comment="Default word cards type set by user",
        ),
        migrations.RemoveField(
            model_name="defaultwordcards",
            name="words_view",
        ),
        migrations.AddField(
            model_name="defaultwordcards",
            name="cards_type",
            field=models.CharField(
                choices=[
                    ("standart", "Стандартный"),
                    ("short", "Короткий"),
                    ("long", "Удлиненный"),
                ],
                default="standart",
                max_length=8,
                verbose_name="Word cards type",
            ),
        ),
    ]
