# Generated by Django 4.2.15 on 2024-09-01 17:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0003_rename_formsgroup_formgroup"),
    ]

    operations = [
        migrations.RenameField(
            model_name="word",
            old_name="images_associations",
            new_name="image_associations",
        ),
    ]
