# Generated by Django 4.2.15 on 2024-09-01 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0004_rename_images_associations_word_image_associations"),
    ]

    operations = [
        migrations.RenameField(
            model_name="word",
            old_name="quotes_associations",
            new_name="quote_associations",
        ),
    ]
