# Generated by Django 4.2.15 on 2024-09-02 11:35

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0005_rename_quotes_associations_word_quote_associations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="slug",
            field=models.SlugField(max_length=1024, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="collection",
            name="title",
            field=models.CharField(
                max_length=32,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure word begin with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    ),
                ],
                verbose_name="Название коллекции",
            ),
        ),
        migrations.AlterField(
            model_name="definition",
            name="slug",
            field=models.SlugField(max_length=1024, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="definition",
            name="text",
            field=models.CharField(
                help_text="Определение слова или фразы",
                max_length=512,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure word begin with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    ),
                ],
                verbose_name="Определение",
            ),
        ),
        migrations.AlterField(
            model_name="definition",
            name="translation",
            field=models.CharField(
                blank=True,
                max_length=512,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure word begin with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    ),
                ],
                verbose_name="Перевод определения",
            ),
        ),
        migrations.AlterField(
            model_name="formgroup",
            name="color",
            field=models.CharField(
                blank=True,
                max_length=7,
                validators=[
                    django.core.validators.MinLengthValidator(7),
                    apps.core.validators.CustomRegexValidator(
                        message="Color must be in hex format.", regex="^#[\\w]+$"
                    ),
                ],
                verbose_name="Цвет группы",
            ),
        ),
        migrations.AlterField(
            model_name="formgroup",
            name="name",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure word begin with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    ),
                ],
                verbose_name="Название группы",
            ),
        ),
        migrations.AlterField(
            model_name="formgroup",
            name="slug",
            field=models.SlugField(max_length=1024, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="formgroup",
            name="translation",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure word begin with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    ),
                ],
                verbose_name="Перевод названия группы",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="slug",
            field=models.SlugField(max_length=1024, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="quoteassociation",
            name="quote_author",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure word begin with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    )
                ],
                verbose_name="Автор Цитаты",
            ),
        ),
        migrations.AlterField(
            model_name="quoteassociation",
            name="text",
            field=models.CharField(
                max_length=256,
                validators=[
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure word begin with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    )
                ],
                verbose_name="Текст цитаты",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=32,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure word begin with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    ),
                ],
                verbose_name="Имя тега",
            ),
        ),
        migrations.AlterField(
            model_name="type",
            name="name",
            field=models.CharField(
                max_length=64,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure word begin with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    ),
                ],
                verbose_name="Имя типа",
            ),
        ),
        migrations.AlterField(
            model_name="type",
            name="name_en",
            field=models.CharField(
                max_length=64,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure word begin with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    ),
                ],
                verbose_name="Имя типа",
            ),
        ),
        migrations.AlterField(
            model_name="type",
            name="name_ru",
            field=models.CharField(
                max_length=64,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure word begin with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    ),
                ],
                verbose_name="Имя типа",
            ),
        ),
        migrations.AlterField(
            model_name="type",
            name="slug",
            field=models.SlugField(max_length=1024, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="usageexample",
            name="slug",
            field=models.SlugField(max_length=1024, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="usageexample",
            name="text",
            field=models.CharField(
                help_text="Пример использования слова или фразы",
                max_length=512,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure word begin with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    ),
                ],
                verbose_name="Пример использования",
            ),
        ),
        migrations.AlterField(
            model_name="usageexample",
            name="translation",
            field=models.CharField(
                blank=True,
                max_length=512,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure word begin with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    ),
                ],
                verbose_name="Перевод примера",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="slug",
            field=models.SlugField(max_length=1024, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="word",
            name="text",
            field=models.CharField(
                max_length=256,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure word begin with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    ),
                ],
                verbose_name="Слово или фраза",
            ),
        ),
        migrations.AlterField(
            model_name="wordtranslation",
            name="slug",
            field=models.SlugField(max_length=1024, unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="wordtranslation",
            name="text",
            field=models.CharField(
                help_text="Перевод слова или фразы на другой язык",
                max_length=256,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure word begin with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    ),
                ],
                verbose_name="Перевод",
            ),
        ),
    ]
