# Generated by Django 4.2.15 on 2024-09-04 15:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("vocabulary", "0007_wordtype_delete_type_alter_word_types"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tag",
            new_name="WordTag",
        ),
        migrations.AlterModelOptions(
            name="wordtag",
            options={
                "get_latest_by": ("created", "modified"),
                "ordering": ("-created", "-modified"),
                "verbose_name": "Word tag",
                "verbose_name_plural": "Теги слова",
            },
        ),
        migrations.AlterModelTableComment(
            name="wordtag",
            table_comment="Word or phrase tags",
        ),
    ]
