# Generated by Django 4.2.15 on 2024-09-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0008_rename_tag_wordtag_alter_wordtag_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="antonym",
            name="note",
            field=models.CharField(
                blank=True,
                help_text="Note for %(class)ss",
                max_length=256,
                verbose_name="Заметка",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="text",
            field=models.CharField(max_length=256, verbose_name="Текст заметки"),
        ),
        migrations.AlterField(
            model_name="synonym",
            name="note",
            field=models.CharField(
                blank=True,
                help_text="Note for %(class)ss",
                max_length=256,
                verbose_name="Заметка",
            ),
        ),
    ]
