# Generated by Django 4.2.15 on 2024-10-07 17:34

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0009_alter_antonym_note_alter_note_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formgroup",
            name="translation",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure word begin with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    )
                ],
                verbose_name="Перевод названия группы",
            ),
        ),
    ]
