# Generated by Django 4.2.15 on 2024-10-08 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0010_alter_formgroup_translation"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="note",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="Текст заметки"
            ),
        ),
        migrations.DeleteModel(
            name="Note",
        ),
    ]
