# Generated by Django 4.2.15 on 2024-10-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0011_word_note_delete_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="usageexample",
            name="source",
            field=models.CharField(
                choices=[
                    ("other", "Other"),
                    ("book", "Book"),
                    ("film", "Film"),
                    ("song", "Song"),
                    ("quote", "Quote"),
                ],
                default="other",
                max_length=64,
                verbose_name="Example source type",
            ),
        ),
        migrations.AddField(
            model_name="usageexample",
            name="source_url",
            field=models.CharField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="Example source hotlink",
            ),
        ),
    ]
