# Generated by Django 4.2.15 on 2024-10-19 12:11

import apps.core.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0012_usageexample_source_usageexample_source_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wordtag",
            name="name",
            field=models.CharField(
                max_length=32,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure word begin with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    ),
                ],
                verbose_name="Имя тега",
            ),
        ),
        migrations.AddConstraint(
            model_name="wordtag",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("author"),
                name="unique_tag_name",
            ),
        ),
    ]
