# Generated by Django 4.2.15 on 2024-10-24 10:10

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0013_alter_wordtag_name_wordtag_unique_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="title",
            field=models.CharField(
                max_length=32,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Digits Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. ",
                        regex="^([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    ),
                ],
                verbose_name="Название коллекции",
            ),
        ),
    ]
