# Generated by Django 4.2.15 on 2024-10-24 14:57

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0014_alter_collection_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="definition",
            name="text",
            field=models.CharField(
                help_text="Определение слова или фразы",
                max_length=512,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    ),
                ],
                verbose_name="Определение",
            ),
        ),
        migrations.AlterField(
            model_name="definition",
            name="translation",
            field=models.CharField(
                blank=True,
                max_length=512,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    ),
                ],
                verbose_name="Перевод определения",
            ),
        ),
        migrations.AlterField(
            model_name="formgroup",
            name="name",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Digits Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. ",
                        regex="^([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    ),
                ],
                verbose_name="Название группы",
            ),
        ),
        migrations.AlterField(
            model_name="formgroup",
            name="translation",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    )
                ],
                verbose_name="Перевод названия группы",
            ),
        ),
        migrations.AlterField(
            model_name="quoteassociation",
            name="quote_author",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    )
                ],
                verbose_name="Автор Цитаты",
            ),
        ),
        migrations.AlterField(
            model_name="quoteassociation",
            name="text",
            field=models.CharField(
                max_length=256,
                validators=[
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    )
                ],
                verbose_name="Текст цитаты",
            ),
        ),
        migrations.AlterField(
            model_name="usageexample",
            name="text",
            field=models.CharField(
                help_text="Пример использования слова или фразы",
                max_length=512,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    ),
                ],
                verbose_name="Пример использования",
            ),
        ),
        migrations.AlterField(
            model_name="usageexample",
            name="translation",
            field=models.CharField(
                blank=True,
                max_length=512,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    ),
                ],
                verbose_name="Перевод примера",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="text",
            field=models.CharField(
                max_length=256,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    ),
                ],
                verbose_name="Слово или фраза",
            ),
        ),
        migrations.AlterField(
            model_name="wordtag",
            name="name",
            field=models.CharField(
                max_length=32,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    ),
                ],
                verbose_name="Имя тега",
            ),
        ),
        migrations.AlterField(
            model_name="wordtranslation",
            name="text",
            field=models.CharField(
                help_text="Перевод слова или фразы на другой язык",
                max_length=256,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    ),
                ],
                verbose_name="Перевод",
            ),
        ),
        migrations.AlterField(
            model_name="wordtype",
            name="name",
            field=models.CharField(
                max_length=64,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    ),
                ],
                verbose_name="Word type name",
            ),
        ),
        migrations.AlterField(
            model_name="wordtype",
            name="name_en",
            field=models.CharField(
                max_length=64,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    ),
                ],
                verbose_name="Word type name",
            ),
        ),
        migrations.AlterField(
            model_name="wordtype",
            name="name_ru",
            field=models.CharField(
                max_length=64,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() ]*)$",
                    ),
                ],
                verbose_name="Word type name",
            ),
        ),
    ]
