# Generated by Django 4.2.15 on 2024-10-27 16:16

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):
    dependencies = [
        (
            "vocabulary",
            "0015_alter_definition_text_alter_definition_translation_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="wordtranslation",
            name="unique_word_translation_in_user_voc",
        ),
        migrations.AddConstraint(
            model_name="wordtranslation",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("text"),
                models.F("author"),
                models.F("language"),
                name="unique_word_translation_in_user_voc",
            ),
        ),
    ]
