# Generated by Django 4.2.15 on 2024-10-28 21:08

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "vocabulary",
            "0016_remove_wordtranslation_unique_word_translation_in_user_voc_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="definition",
            name="text",
            field=models.CharField(
                help_text="Определение слова или фразы",
                max_length=512,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Digits Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. ",
                        regex="^([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    ),
                ],
                verbose_name="Определение",
            ),
        ),
        migrations.AlterField(
            model_name="usageexample",
            name="text",
            field=models.CharField(
                help_text="Пример использования слова или фразы",
                max_length=512,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Digits Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. ",
                        regex="^([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    ),
                ],
                verbose_name="Пример использования",
            ),
        ),
    ]
