# Generated by Django 4.2.15 on 2024-12-16 09:37

import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocabulary", "0017_alter_definition_text_alter_usageexample_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="defaultwordcards",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Настройка вида карточек слов пользователя по умолчанию",
                "verbose_name_plural": "Настройки вида карточек слов пользователя по умолчанию",
            },
        ),
        migrations.AlterModelOptions(
            name="wordtag",
            options={
                "get_latest_by": ("created", "modified"),
                "ordering": ("-created", "-modified"),
                "verbose_name": "Теги слова",
                "verbose_name_plural": "Теги слова",
            },
        ),
        migrations.AlterModelOptions(
            name="wordtype",
            options={
                "get_latest_by": ("created", "modified"),
                "ordering": ("-created", "-modified", "-id"),
                "verbose_name": "Тип слова",
                "verbose_name_plural": "Типы слов",
            },
        ),
        migrations.AlterModelTableComment(
            name="defaultwordcards",
            table_comment="Вид карточек слов пользователя по умолчанию",
        ),
        migrations.AlterModelTableComment(
            name="wordtag",
            table_comment="Теги слов или фраз",
        ),
        migrations.AlterModelTableComment(
            name="wordtype",
            table_comment="Типы слов или фраз",
        ),
        migrations.AlterField(
            model_name="antonym",
            name="note",
            field=models.CharField(
                blank=True,
                help_text="Заметка для %(class)ss",
                max_length=256,
                verbose_name="Заметка",
            ),
        ),
        migrations.AlterField(
            model_name="defaultwordcards",
            name="cards_type",
            field=models.CharField(
                choices=[
                    ("standart", "Стандартный"),
                    ("short", "Сокращенный"),
                    ("long", "Пролонгированный"),
                ],
                default="standart",
                max_length=8,
                verbose_name="Word cards type",
            ),
        ),
        migrations.AlterField(
            model_name="definition",
            name="translation",
            field=models.CharField(
                blank=True,
                max_length=512,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    ),
                ],
                verbose_name="Перевод определения",
            ),
        ),
        migrations.AlterField(
            model_name="formgroup",
            name="translation",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    )
                ],
                verbose_name="Перевод названия группы",
            ),
        ),
        migrations.AlterField(
            model_name="quoteassociation",
            name="quote_author",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    )
                ],
                verbose_name="Автор Цитаты",
            ),
        ),
        migrations.AlterField(
            model_name="quoteassociation",
            name="text",
            field=models.CharField(
                max_length=256,
                validators=[
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    )
                ],
                verbose_name="Текст цитаты",
            ),
        ),
        migrations.AlterField(
            model_name="synonym",
            name="note",
            field=models.CharField(
                blank=True,
                help_text="Заметка для %(class)ss",
                max_length=256,
                verbose_name="Заметка",
            ),
        ),
        migrations.AlterField(
            model_name="usageexample",
            name="source",
            field=models.CharField(
                choices=[
                    ("other", "Другое"),
                    ("book", "Книга"),
                    ("film", "Фильм"),
                    ("song", "Песня"),
                    ("quote", "Quote"),
                ],
                default="other",
                max_length=64,
                verbose_name="Источник примера",
            ),
        ),
        migrations.AlterField(
            model_name="usageexample",
            name="source_url",
            field=models.CharField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="Ссылка на источник примера",
            ),
        ),
        migrations.AlterField(
            model_name="usageexample",
            name="translation",
            field=models.CharField(
                blank=True,
                max_length=512,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    ),
                ],
                verbose_name="Перевод примера",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="text",
            field=models.CharField(
                max_length=256,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    ),
                ],
                verbose_name="Слово или фраза",
            ),
        ),
        migrations.AlterField(
            model_name="wordtag",
            name="name",
            field=models.CharField(
                max_length=32,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    ),
                ],
                verbose_name="Имя тега",
            ),
        ),
        migrations.AlterField(
            model_name="wordtranslation",
            name="text",
            field=models.CharField(
                help_text="Перевод слова или фразы на другой язык",
                max_length=256,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    ),
                ],
                verbose_name="Перевод",
            ),
        ),
        migrations.AlterField(
            model_name="wordtype",
            name="name",
            field=models.CharField(
                max_length=64,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    ),
                ],
                verbose_name="Имя типа слова",
            ),
        ),
        migrations.AlterField(
            model_name="wordtype",
            name="name_en",
            field=models.CharField(
                max_length=64,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    ),
                ],
                verbose_name="Имя типа слова",
            ),
        ),
        migrations.AlterField(
            model_name="wordtype",
            name="name_ru",
            field=models.CharField(
                max_length=64,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    ),
                ],
                verbose_name="Имя типа слова",
            ),
        ),
    ]
