# Generated by Django 4.2.15 on 2024-12-16 09:42

import apps.core.validators
import apps.vocabulary.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("languages", "0008_alter_language_options_and_more"),
        (
            "vocabulary",
            "0018_alter_defaultwordcards_options_alter_wordtag_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="antonym",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-from_word__created", "-created"),
                "verbose_name": "Antonym",
                "verbose_name_plural": "Antonyms",
            },
        ),
        migrations.AlterModelOptions(
            name="collection",
            options={
                "get_latest_by": ("created", "modified"),
                "ordering": ("-created", "-modified", "-id"),
                "verbose_name": "Collection",
                "verbose_name_plural": "Collections",
            },
        ),
        migrations.AlterModelOptions(
            name="defaultwordcards",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "User default word cards type setting",
                "verbose_name_plural": "User default word cards type settings",
            },
        ),
        migrations.AlterModelOptions(
            name="definition",
            options={
                "get_latest_by": ("created", "modified"),
                "ordering": ("-created", "-modified", "-id"),
                "verbose_name": "Definition",
                "verbose_name_plural": "Definitions",
            },
        ),
        migrations.AlterModelOptions(
            name="favoritecollection",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Favorite collection",
                "verbose_name_plural": "Favorite collections",
            },
        ),
        migrations.AlterModelOptions(
            name="favoriteword",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Favorite word",
                "verbose_name_plural": "Favorite words",
            },
        ),
        migrations.AlterModelOptions(
            name="form",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-from_word__created", "-created"),
                "verbose_name": "Form",
                "verbose_name_plural": "Forms",
            },
        ),
        migrations.AlterModelOptions(
            name="formgroup",
            options={
                "get_latest_by": ("created", "modified"),
                "ordering": ("-created", "-modified", "name"),
                "verbose_name": "Forms group",
                "verbose_name_plural": "Forms groups",
            },
        ),
        migrations.AlterModelOptions(
            name="imageassociation",
            options={
                "get_latest_by": ("created", "modified"),
                "ordering": ("-created", "-modified"),
                "verbose_name": "Image-association",
                "verbose_name_plural": "Image-associations",
            },
        ),
        migrations.AlterModelOptions(
            name="quoteassociation",
            options={
                "get_latest_by": ("created", "modified"),
                "ordering": ("-created", "-modified"),
                "verbose_name": "Quote-association",
                "verbose_name_plural": "Quote-associations",
            },
        ),
        migrations.AlterModelOptions(
            name="similar",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-from_word__created", "-created"),
                "verbose_name": "Similar",
                "verbose_name_plural": "Similars",
            },
        ),
        migrations.AlterModelOptions(
            name="synonym",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-from_word__created", "-created"),
                "verbose_name": "Synonyms",
                "verbose_name_plural": "Synonyms",
            },
        ),
        migrations.AlterModelOptions(
            name="usageexample",
            options={
                "get_latest_by": ("created", "modified"),
                "ordering": ("-created", "-modified"),
                "verbose_name": "Usage example",
                "verbose_name_plural": "Usage examples",
            },
        ),
        migrations.AlterModelOptions(
            name="word",
            options={
                "get_latest_by": ("created", "modified"),
                "ordering": ("-created", "-modified", "-id"),
                "verbose_name": "Word or phrase",
                "verbose_name_plural": "Words and phrases",
            },
        ),
        migrations.AlterModelOptions(
            name="worddefinitions",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Word definition (intermediary model)",
                "verbose_name_plural": "Word definitions (intermediary model)",
            },
        ),
        migrations.AlterModelOptions(
            name="wordimageassociations",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Word image-association (intermediary model)",
                "verbose_name_plural": "Words image-associations (intermediary model)",
            },
        ),
        migrations.AlterModelOptions(
            name="wordquoteassociations",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Word quote-association (intermediary model)",
                "verbose_name_plural": "Words quote-associations (intermediary model)",
            },
        ),
        migrations.AlterModelOptions(
            name="wordsformgroups",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Word form group (intermediary model)",
                "verbose_name_plural": "Words form groups (intermediary model)",
            },
        ),
        migrations.AlterModelOptions(
            name="wordsincollections",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Word in collection (intermediary model)",
                "verbose_name_plural": "Words in collections (intermediary model)",
            },
        ),
        migrations.AlterModelOptions(
            name="wordtag",
            options={
                "get_latest_by": ("created", "modified"),
                "ordering": ("-created", "-modified"),
                "verbose_name": "Word tag",
                "verbose_name_plural": "Word tags",
            },
        ),
        migrations.AlterModelOptions(
            name="wordtranslation",
            options={
                "get_latest_by": ("created", "modified"),
                "ordering": ("-created", "-modified"),
                "verbose_name": "Translation",
                "verbose_name_plural": "Translations",
            },
        ),
        migrations.AlterModelOptions(
            name="wordtranslations",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Word translation (intermediary model)",
                "verbose_name_plural": "Word translations (intermediary model)",
            },
        ),
        migrations.AlterModelOptions(
            name="wordtype",
            options={
                "get_latest_by": ("created", "modified"),
                "ordering": ("-created", "-modified", "-id"),
                "verbose_name": "Word type",
                "verbose_name_plural": "Word types",
            },
        ),
        migrations.AlterModelOptions(
            name="wordusageexamples",
            options={
                "get_latest_by": ("created",),
                "ordering": ("-created",),
                "verbose_name": "Word usage example (intermediary model)",
                "verbose_name_plural": "Word usage examples (intermediary model)",
            },
        ),
        migrations.AlterModelTableComment(
            name="antonym",
            table_comment="Words antonyms",
        ),
        migrations.AlterModelTableComment(
            name="collection",
            table_comment="Collections of words and phrases",
        ),
        migrations.AlterModelTableComment(
            name="defaultwordcards",
            table_comment="Default word cards type set by user",
        ),
        migrations.AlterModelTableComment(
            name="definition",
            table_comment="Definitions for words and phrases",
        ),
        migrations.AlterModelTableComment(
            name="favoritecollection",
            table_comment="Users favorite collections",
        ),
        migrations.AlterModelTableComment(
            name="favoriteword",
            table_comment="Users favorite words",
        ),
        migrations.AlterModelTableComment(
            name="form",
            table_comment="Words forms",
        ),
        migrations.AlterModelTableComment(
            name="formgroup",
            table_comment="Groups of possible word forms in language",
        ),
        migrations.AlterModelTableComment(
            name="imageassociation",
            table_comment="Image-associations for words and phrases",
        ),
        migrations.AlterModelTableComment(
            name="quoteassociation",
            table_comment="Quote-associations for words and phrases",
        ),
        migrations.AlterModelTableComment(
            name="similar",
            table_comment="Similar words",
        ),
        migrations.AlterModelTableComment(
            name="synonym",
            table_comment="Words synonyms",
        ),
        migrations.AlterModelTableComment(
            name="usageexample",
            table_comment="Usage examples for words and phrases",
        ),
        migrations.AlterModelTableComment(
            name="word",
            table_comment="Users words and phrases",
        ),
        migrations.AlterModelTableComment(
            name="worddefinitions",
            table_comment="Words and definitions intermediary model",
        ),
        migrations.AlterModelTableComment(
            name="wordimageassociations",
            table_comment="Words and image-associations intermediary model",
        ),
        migrations.AlterModelTableComment(
            name="wordquoteassociations",
            table_comment="Words and quote-associations intermediary model",
        ),
        migrations.AlterModelTableComment(
            name="wordsformgroups",
            table_comment="Intermediary model for words and form groups",
        ),
        migrations.AlterModelTableComment(
            name="wordsincollections",
            table_comment="Words and collections intermediary model",
        ),
        migrations.AlterModelTableComment(
            name="wordtag",
            table_comment="Word or phrase tags",
        ),
        migrations.AlterModelTableComment(
            name="wordtranslation",
            table_comment="Translations for words and phrases",
        ),
        migrations.AlterModelTableComment(
            name="wordtranslations",
            table_comment="Words and its translations intermediary model",
        ),
        migrations.AlterModelTableComment(
            name="wordtype",
            table_comment="Word or phrase types",
        ),
        migrations.AlterModelTableComment(
            name="wordusageexamples",
            table_comment="Words and usage examples intermediary model",
        ),
        migrations.AlterField(
            model_name="antonym",
            name="note",
            field=models.CharField(
                blank=True,
                help_text="Note for %(class)ss",
                max_length=256,
                verbose_name="Note",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="description",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="title",
            field=models.CharField(
                max_length=32,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Digits Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. ",
                        regex="^([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    ),
                ],
                verbose_name="Collection title",
            ),
        ),
        migrations.AlterField(
            model_name="collection",
            name="words",
            field=models.ManyToManyField(
                blank=True,
                related_name="collections",
                through="vocabulary.WordsInCollections",
                to="vocabulary.word",
                verbose_name="Word in collection",
            ),
        ),
        migrations.AlterField(
            model_name="defaultwordcards",
            name="cards_type",
            field=models.CharField(
                choices=[
                    ("standart", "Standart"),
                    ("short", "Short"),
                    ("long", "Long"),
                ],
                default="standart",
                max_length=8,
                verbose_name="Word cards type",
            ),
        ),
        migrations.AlterField(
            model_name="definition",
            name="language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="definitions",
                to="languages.language",
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="definition",
            name="text",
            field=models.CharField(
                help_text="A definition of a word or phrase",
                max_length=512,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Digits Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. ",
                        regex="^([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    ),
                ],
                verbose_name="Definition",
            ),
        ),
        migrations.AlterField(
            model_name="definition",
            name="translation",
            field=models.CharField(
                blank=True,
                max_length=512,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    ),
                ],
                verbose_name="A translation of the definition",
            ),
        ),
        migrations.AlterField(
            model_name="favoritecollection",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_for",
                to="vocabulary.collection",
                verbose_name="Collection",
            ),
        ),
        migrations.AlterField(
            model_name="favoriteword",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="favorite_for",
                to="vocabulary.word",
                verbose_name="Word",
            ),
        ),
        migrations.AlterField(
            model_name="formgroup",
            name="color",
            field=models.CharField(
                blank=True,
                max_length=7,
                validators=[
                    django.core.validators.MinLengthValidator(7),
                    apps.core.validators.CustomRegexValidator(
                        message="Color must be in hex format.", regex="^#[\\w]+$"
                    ),
                ],
                verbose_name="Group color",
            ),
        ),
        migrations.AlterField(
            model_name="formgroup",
            name="language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="form_groups",
                to="languages.language",
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="formgroup",
            name="name",
            field=models.CharField(
                max_length=64,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Digits Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. ",
                        regex="^([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    ),
                ],
                verbose_name="Group name",
            ),
        ),
        migrations.AlterField(
            model_name="formgroup",
            name="translation",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    )
                ],
                verbose_name="Group name translation",
            ),
        ),
        migrations.AlterField(
            model_name="imageassociation",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.vocabulary.models.image_associations_path,
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="quoteassociation",
            name="quote_author",
            field=models.CharField(
                blank=True,
                max_length=64,
                validators=[
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    )
                ],
                verbose_name="Quote author",
            ),
        ),
        migrations.AlterField(
            model_name="quoteassociation",
            name="text",
            field=models.CharField(
                max_length=256,
                validators=[
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    )
                ],
                verbose_name="Quote text",
            ),
        ),
        migrations.AlterField(
            model_name="synonym",
            name="note",
            field=models.CharField(
                blank=True,
                help_text="Note for %(class)ss",
                max_length=256,
                verbose_name="Note",
            ),
        ),
        migrations.AlterField(
            model_name="usageexample",
            name="language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="examples",
                to="languages.language",
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="usageexample",
            name="source",
            field=models.CharField(
                choices=[
                    ("other", "Other"),
                    ("book", "Book"),
                    ("film", "Film"),
                    ("song", "Song"),
                    ("quote", "Quote"),
                ],
                default="other",
                max_length=64,
                verbose_name="Example source type",
            ),
        ),
        migrations.AlterField(
            model_name="usageexample",
            name="source_url",
            field=models.CharField(
                blank=True,
                max_length=512,
                null=True,
                verbose_name="Example source hotlink",
            ),
        ),
        migrations.AlterField(
            model_name="usageexample",
            name="text",
            field=models.CharField(
                help_text="An usage example of a word or phrase",
                max_length=512,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Digits Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. ",
                        regex="^([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    ),
                ],
                verbose_name="Usage example",
            ),
        ),
        migrations.AlterField(
            model_name="usageexample",
            name="translation",
            field=models.CharField(
                blank=True,
                max_length=512,
                validators=[
                    django.core.validators.MinLengthValidator(2),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    ),
                ],
                verbose_name="A translation of the example",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="activity_status",
            field=models.CharField(
                choices=[("I", "Inactive"), ("A", "Active"), ("M", "Mastered")],
                default="I",
                max_length=8,
                verbose_name="Activity status",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="antonyms",
            field=models.ManyToManyField(
                blank=True,
                help_text="Words with opposite meanings",
                through="vocabulary.Antonym",
                to="vocabulary.word",
                verbose_name="Antonyms",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="definitions",
            field=models.ManyToManyField(
                blank=True,
                related_name="words",
                through="vocabulary.WordDefinitions",
                to="vocabulary.definition",
                verbose_name="Definitions",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="examples",
            field=models.ManyToManyField(
                blank=True,
                related_name="words",
                through="vocabulary.WordUsageExamples",
                to="vocabulary.usageexample",
                verbose_name="Usage example",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="form_groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="words",
                through="vocabulary.WordsFormGroups",
                to="vocabulary.formgroup",
                verbose_name="Word form groups",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="forms",
            field=models.ManyToManyField(
                blank=True,
                help_text="Word forms",
                through="vocabulary.Form",
                to="vocabulary.word",
                verbose_name="Forms",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="image_associations",
            field=models.ManyToManyField(
                blank=True,
                related_name="words",
                through="vocabulary.WordImageAssociations",
                to="vocabulary.imageassociation",
                verbose_name="Image association",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="is_problematic",
            field=models.BooleanField(
                default=False, verbose_name="Is the word problematic for you"
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="words",
                to="languages.language",
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="last_exercise_date",
            field=models.DateTimeField(
                editable=False, null=True, verbose_name="Last exercise date"
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="note",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="Note text"
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="quote_associations",
            field=models.ManyToManyField(
                blank=True,
                related_name="words",
                through="vocabulary.WordQuoteAssociations",
                to="vocabulary.quoteassociation",
                verbose_name="Quote association",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="similars",
            field=models.ManyToManyField(
                blank=True,
                help_text="Words with similar pronunciation or spelling",
                through="vocabulary.Similar",
                to="vocabulary.word",
                verbose_name="Similars",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="synonyms",
            field=models.ManyToManyField(
                blank=True,
                help_text="Words with similar meanings",
                through="vocabulary.Synonym",
                to="vocabulary.word",
                verbose_name="Synonyms",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="words",
                to="vocabulary.wordtag",
                verbose_name="Word tags",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="text",
            field=models.CharField(
                max_length=256,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    ),
                ],
                verbose_name="Word or phrase",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="translations",
            field=models.ManyToManyField(
                blank=True,
                related_name="words",
                through="vocabulary.WordTranslations",
                to="vocabulary.wordtranslation",
                verbose_name="Translations",
            ),
        ),
        migrations.AlterField(
            model_name="worddefinitions",
            name="definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="vocabulary.definition",
                verbose_name="Definition",
            ),
        ),
        migrations.AlterField(
            model_name="worddefinitions",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="vocabulary.word",
                verbose_name="Word",
            ),
        ),
        migrations.AlterField(
            model_name="wordimageassociations",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="vocabulary.imageassociation",
                verbose_name="Image association",
            ),
        ),
        migrations.AlterField(
            model_name="wordimageassociations",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="vocabulary.word",
                verbose_name="Word",
            ),
        ),
        migrations.AlterField(
            model_name="wordquoteassociations",
            name="quote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="vocabulary.quoteassociation",
                verbose_name="Quote association",
            ),
        ),
        migrations.AlterField(
            model_name="wordquoteassociations",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="vocabulary.word",
                verbose_name="Word",
            ),
        ),
        migrations.AlterField(
            model_name="wordsformgroups",
            name="forms_group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s",
                to="vocabulary.formgroup",
                verbose_name="Forms group",
            ),
        ),
        migrations.AlterField(
            model_name="wordsformgroups",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="vocabulary.word",
                verbose_name="Word",
            ),
        ),
        migrations.AlterField(
            model_name="wordsincollections",
            name="collection",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="vocabulary.collection",
                verbose_name="Collection",
            ),
        ),
        migrations.AlterField(
            model_name="wordsincollections",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="vocabulary.word",
                verbose_name="Word",
            ),
        ),
        migrations.AlterField(
            model_name="wordtag",
            name="name",
            field=models.CharField(
                max_length=32,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    ),
                ],
                verbose_name="Tag name",
            ),
        ),
        migrations.AlterField(
            model_name="wordtranslation",
            name="language",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="word_translations",
                to="languages.language",
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="wordtranslation",
            name="text",
            field=models.CharField(
                help_text="A translation of a word or phrase",
                max_length=256,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    ),
                ],
                verbose_name="Translation",
            ),
        ),
        migrations.AlterField(
            model_name="wordtranslations",
            name="translation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="vocabulary.wordtranslation",
                verbose_name="Translation",
            ),
        ),
        migrations.AlterField(
            model_name="wordtranslations",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="vocabulary.word",
                verbose_name="Word",
            ),
        ),
        migrations.AlterField(
            model_name="wordtype",
            name="name",
            field=models.CharField(
                max_length=64,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    ),
                ],
                verbose_name="Word type name",
            ),
        ),
        migrations.AlterField(
            model_name="wordtype",
            name="name_en",
            field=models.CharField(
                max_length=64,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    ),
                ],
                verbose_name="Word type name",
            ),
        ),
        migrations.AlterField(
            model_name="wordtype",
            name="name_ru",
            field=models.CharField(
                max_length=64,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.MinLengthValidator(1),
                    apps.core.validators.CustomRegexValidator(
                        message="Acceptable characters: Letters from any language, Hyphen, Exclamation point, Question mark, Dot, Comma, Colon, Apostrophe, Slash. Make sure text begins with a letter.",
                        regex="^(\\p{L}+)([\\p{L}-!?.,:/&'`’() \\d]*)$",
                    ),
                ],
                verbose_name="Word type name",
            ),
        ),
        migrations.AlterField(
            model_name="wordusageexamples",
            name="example",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="vocabulary.usageexample",
                verbose_name="Usage example",
            ),
        ),
        migrations.AlterField(
            model_name="wordusageexamples",
            name="word",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s",
                to="vocabulary.word",
                verbose_name="Word",
            ),
        ),
    ]
